"""Export vectorAddKernel as HSACO + C header.

Run with:
    python export_vec_add.py

Outputs:
    artifacts/vec_add.hsaco
    artifacts/vec_add.h    — C header with hipModuleLoad helpers
"""
import os
import re
import sys

os.environ.setdefault("FLYDSL_RUNTIME_ENABLE_CACHE", "0")

import torch
import flydsl.compiler as flyc
import flydsl.expr as fx


# ── Kernel definition ─────────────────────────────────────────────────────────

@flyc.kernel
def vectorAddKernel(
    A: fx.Tensor, B: fx.Tensor, C: fx.Tensor,
    block_dim: fx.Constexpr[int],
    n: fx.Int32,
):
    bid = fx.block_idx.x
    tid = fx.thread_idx.x

    bid_i32 = fx.arith.index_cast(fx.T.i32(), bid)
    tid_i32 = fx.arith.index_cast(fx.T.i32(), tid)
    blk_i32 = fx.arith.constant(block_dim, type=fx.T.i32())
    global_i = fx.arith.addi(fx.arith.muli(bid_i32, blk_i32), tid_i32)
    in_bounds = fx.arith.cmpi(fx.arith.CmpIPredicate.slt, global_i, n)

    if in_bounds:
        tA = fx.logical_divide(A, fx.make_layout(block_dim, 1))
        tB = fx.logical_divide(B, fx.make_layout(block_dim, 1))
        tC = fx.logical_divide(C, fx.make_layout(block_dim, 1))

        tA = fx.slice(tA, (None, bid))
        tB = fx.slice(tB, (None, bid))
        tC = fx.slice(tC, (None, bid))

        tA = fx.logical_divide(tA, fx.make_layout(1, 1))
        tB = fx.logical_divide(tB, fx.make_layout(1, 1))
        tC = fx.logical_divide(tC, fx.make_layout(1, 1))

        RABTy = fx.MemRefType.get(fx.T.f32(), fx.LayoutType.get(1, 1),
                                  fx.AddressSpace.Register)
        copyAtom = fx.make_copy_atom(fx.UniversalCopy32b(), fx.Float32)
        rA = fx.memref_alloca(RABTy, fx.make_layout(1, 1))
        rB = fx.memref_alloca(RABTy, fx.make_layout(1, 1))
        rC = fx.memref_alloca(RABTy, fx.make_layout(1, 1))

        fx.copy_atom_call(copyAtom, fx.slice(tA, (None, tid)), rA)
        fx.copy_atom_call(copyAtom, fx.slice(tB, (None, tid)), rB)

        vC = fx.arith.addf(fx.memref_load_vec(rA), fx.memref_load_vec(rB))
        fx.memref_store_vec(vC, rC)
        fx.copy_atom_call(copyAtom, rC, fx.slice(tC, (None, tid)))


@flyc.jit
def vectorAdd(
    A: fx.Tensor, B: fx.Tensor, C: fx.Tensor,
    n: fx.Int32,
    const_n: fx.Constexpr[int],
    stream: fx.Stream = fx.Stream(None),
):
    block_dim = 64
    grid_x = (n + block_dim - 1) // block_dim
    vectorAddKernel(A, B, C, block_dim, n).launch(
        grid=(grid_x, 1, 1), block=[block_dim, 1, 1], stream=stream,
    )


# ── Compilation ───────────────────────────────────────────────────────────────

def _compile_and_get_ir():
    n = 128
    A = torch.zeros(n, dtype=torch.float32)
    B = torch.zeros(n, dtype=torch.float32)
    C = torch.zeros(n, dtype=torch.float32)
    prev = os.environ.get("COMPILE_ONLY")
    os.environ["COMPILE_ONLY"] = "1"
    try:
        vectorAdd(A, B, C, n, n)
    finally:
        if prev is None:
            os.environ.pop("COMPILE_ONLY", None)
        else:
            os.environ["COMPILE_ONLY"] = prev
    artifacts = list(vectorAdd._mem_cache.values())
    if not artifacts:
        raise RuntimeError("_mem_cache is empty after compilation")
    return artifacts[0]._ir_text


# ── MLIR binary extraction ────────────────────────────────────────────────────

def _decode_mlir_bin(ir_text: str, start: int) -> bytes:
    marker = 'bin = "'
    pos = ir_text.find(marker, start)
    if pos == -1:
        raise ValueError("'bin = \"' not found in IR text after position %d" % start)
    i = pos + len(marker)
    result = bytearray()
    while i < len(ir_text):
        c = ir_text[i]
        if c == '\\':
            nxt = ir_text[i + 1]
            if nxt == '\\':
                result.append(ord('\\'))
                i += 2
            elif nxt == '"':
                result.append(ord('"'))
                i += 2
            else:
                result.append(int(ir_text[i + 1: i + 3], 16))
                i += 3
        elif c == '"':
            break
        else:
            result.append(ord(c))
            i += 1
    return bytes(result)


def _extract_hsaco(ir_text: str, prefer_no_wave64: bool = True) -> bytes:
    if prefer_no_wave64:
        anchor = ir_text.find("no_wave64")
        if anchor == -1:
            print("Warning: no_wave64 variant not found, falling back to first object")
            anchor = 0
    else:
        anchor = 0
    return _decode_mlir_bin(ir_text, anchor)


def _find_kernel_name(ir_text: str) -> str:
    m = re.search(r'#gpu\.kernel_metadata<"([^"]+)"', ir_text)
    return m.group(1) if m else "vectorAddKernel_0"


# ── C header template ─────────────────────────────────────────────────────────

_HEADER = """\
/* Auto-generated by export_vec_add.py — do not edit.
 *
 * HSACO ELF for {kernel_name} (gfx1201, wave32/RDNA4).
 * Computes:  C[i] = A[i] + B[i]  for i in [0, n).
 * Grid:   ceil(n / 64) x 1 x 1
 * Block:  64 x 1 x 1
 */
#pragma once
#include <hip/hip_runtime.h>
#include <stdint.h>
#include <stdio.h>

typedef struct {{
    hipModule_t   module;
    hipFunction_t func;
}} vec_add_Module_t;

static inline int vec_add_Module_Load(vec_add_Module_t *m, const char *hsaco_path) {{
    hipError_t err = hipModuleLoad(&m->module, hsaco_path);
    if (err != hipSuccess) {{
        fprintf(stderr, "vec_add: hipModuleLoad(%s): %s\\n", hsaco_path, hipGetErrorString(err));
        return (int)err;
    }}
    err = hipModuleGetFunction(&m->func, m->module, "{kernel_name}");
    if (err != hipSuccess) {{
        fprintf(stderr, "vec_add: hipModuleGetFunction: %s\\n", hipGetErrorString(err));
        (void)hipModuleUnload(m->module);
        return (int)err;
    }}
    return 0;
}}

static inline void vec_add_Module_Unload(vec_add_Module_t *m) {{
    if (m->module) (void)hipModuleUnload(m->module);
    m->module = NULL;
    m->func   = NULL;
}}

static inline int vec_add_wrapper(
        const vec_add_Module_t *m,
        hipDeviceptr_t d_A,
        hipDeviceptr_t d_B,
        hipDeviceptr_t d_C,
        int32_t n,
        hipStream_t stream) {{
    unsigned int grid_x = ((unsigned int)n + 63u) / 64u;
    void *args[] = {{ &d_A, &d_B, &d_C, &n }};
    hipError_t err = hipModuleLaunchKernel(
            m->func,
            grid_x, 1, 1,
            64,     1, 1,
            0, stream, args, NULL);
    if (err != hipSuccess) {{
        fprintf(stderr, "vec_add: hipModuleLaunchKernel: %s\\n", hipGetErrorString(err));
        return (int)err;
    }}
    return 0;
}}
"""


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    ir_text = _compile_and_get_ir()
    kernel_name = _find_kernel_name(ir_text)
    print(f"Kernel: {kernel_name}  IR: {len(ir_text):,} chars")

    hsaco = _extract_hsaco(ir_text, prefer_no_wave64=True)
    if hsaco[:4] != b"\x7fELF":
        raise RuntimeError(f"Expected ELF magic, got: {hsaco[:8].hex()}")

    artifacts_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "artifacts")
    os.makedirs(artifacts_dir, exist_ok=True)

    hsaco_path  = os.path.join(artifacts_dir, "vec_add.hsaco")
    header_path = os.path.join(artifacts_dir, "vec_add.h")

    with open(hsaco_path, "wb") as f:
        f.write(hsaco)
    print(f"  Wrote {len(hsaco):,} bytes → {hsaco_path}")

    with open(header_path, "w") as f:
        f.write(_HEADER.format(kernel_name=kernel_name))
    print(f"  Wrote header → {header_path}")
