"""Export rdna_fp8_unfactored_lstm_gemm as HSACO + C header.

Single fused dispatch: hh_fp8 @ W_fused_fp8 + LSTM gate epilogue → fp8 h output
(fixed-scale 1/448) with cell state c updated in-place. The per-token quantize is
fused into the epilogue, so there is NO separate quantize kernel (unlike the
dual-GEMM export).

Run with:
    python fly/export_fp8_unfactored_lstm.py                       # defaults (H=1024)
    python fly/export_fp8_unfactored_lstm.py --H 1024 --M 512      # single config
    python fly/export_fp8_unfactored_lstm.py --config fly/export_configs/rdna_fp8_unfactored_lstm.toml

Outputs per config (in fly/artifacts/):
    rdna_fp8_unfactored_lstm_H{H}.hsaco + .h
"""
import argparse
import os
import re
import sys

try:
    import tomllib
except ModuleNotFoundError:
    try:
        import tomli as tomllib  # type: ignore[no-redef]
    except ModuleNotFoundError:
        tomllib = None  # type: ignore[assignment]

os.environ.setdefault("FLYDSL_RUNTIME_ENABLE_CACHE", "0")

import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rdna_fp8_unfactored_lstm_gemm import (
    compile_fp8_unfactored_lstm_gemm,
    compile_fp8_unfactored_lstm_gemm_persistent,
)


# ── Tile / wave config (mirrors compile_fp8_unfactored_lstm_gemm defaults) ─────
# waves_m, waves_n are fixed at (1, 2) in the kernel; tiles are the compile defaults.
TILE_M    = 32
TILE_N_H  = 32
WAVES_M   = 1
WAVES_N   = 2


def _compute_config(M: int, H: int) -> dict:
    threads_per_block = WAVES_M * WAVES_N * 32
    grid_h = H // TILE_N_H
    return dict(
        tile_m=TILE_M,
        tile_n_h=TILE_N_H,
        threads_per_block=threads_per_block,
        grid_h=grid_h,
        total_blocks=(M // TILE_M) * grid_h,
    )


def _load_configs(path: str, default_m: int = 512) -> list[tuple[int, int]]:
    if tomllib is None:
        raise RuntimeError(
            "tomllib not available — upgrade to Python 3.11+ or `pip install tomli`"
        )
    with open(path, "rb") as f:
        data = tomllib.load(f)
    return [(int(c.get("M", default_m)), int(c["H"])) for c in data["configs"]]


# ── Compilation ───────────────────────────────────────────────────────────────

def _compile_and_get_ir(M: int, H: int) -> str:
    FH = 4 * H
    launcher    = compile_fp8_unfactored_lstm_gemm(B=M, H=H)
    h_fp8_out   = torch.zeros(M, H, dtype=torch.uint8)
    c_inout     = torch.zeros(M, H, dtype=torch.float32)
    hh          = torch.zeros(M, H, dtype=torch.uint8)
    scale_hh    = torch.zeros(M, dtype=torch.float32)
    w_fused     = torch.zeros(FH // 16, H // 16, 2, 16, 8, dtype=torch.uint8)  # preshuffled fp8
    scale_wf    = torch.zeros(FH, dtype=torch.float32)
    bias        = torch.zeros(FH, dtype=torch.float32)
    ih_t        = torch.zeros(M, H, 4, dtype=torch.float16)                    # [B, H, 4] interleaved
    prev = os.environ.get("COMPILE_ONLY")
    os.environ["COMPILE_ONLY"] = "1"
    try:
        launcher(h_fp8_out, c_inout, hh, scale_hh, w_fused, scale_wf, bias, ih_t, 0, M)
    finally:
        if prev is None:
            os.environ.pop("COMPILE_ONLY", None)
        else:
            os.environ["COMPILE_ONLY"] = prev
    artifacts = list(launcher._mem_cache.values())
    if not artifacts:
        raise RuntimeError("_mem_cache is empty after unfactored-LSTM compilation")
    return artifacts[0]._ir_text


# ── MLIR binary extraction ────────────────────────────────────────────────────

def _decode_mlir_bin(ir_text: str, start: int) -> bytes:
    marker = 'bin = "'
    pos = ir_text.find(marker, start)
    if pos == -1:
        raise ValueError("'bin = \"' not found in IR text after position %d" % start)
    i = pos + len(marker)
    result = bytearray()
    while i < len(ir_text):
        c = ir_text[i]
        if c == '\\':
            nxt = ir_text[i + 1]
            if nxt == '\\':
                result.append(ord('\\'))
                i += 2
            elif nxt == '"':
                result.append(ord('"'))
                i += 2
            else:
                result.append(int(ir_text[i + 1: i + 3], 16))
                i += 3
        elif c == '"':
            break
        else:
            result.append(ord(c))
            i += 1
    return bytes(result)


def _extract_hsaco(ir_text: str, prefer_no_wave64: bool = True) -> bytes:
    if prefer_no_wave64:
        anchor = ir_text.find("no_wave64")
        if anchor == -1:
            print("Warning: no_wave64 variant not found, falling back to first object")
            anchor = 0
    else:
        anchor = 0
    return _decode_mlir_bin(ir_text, anchor)


def _find_kernel_name(ir_text: str) -> str:
    m = re.search(r'#gpu\.kernel_metadata<"([^"]+)"', ir_text)
    return m.group(1) if m else "kernel_0"


# ── C header template ───────────────────────────────────────────────────────--

_HEADER = """\
/* Auto-generated by export_fp8_unfactored_lstm.py — do not edit.
 *
 * HSACO ELF for {kernel_name} (gfx1201, wave32/RDNA4).
 *
 * Fused unfactored LSTM step (single dispatch):
 *   gates = hh_fp8[B,H] @ W_fused_fp8[H,4H]^T + bias[4H] + ih_t[B,4H]
 *   i,f,o = sigmoid_hard; g = tanh_hard; c = f*c + i*g; h = o*tanh(c)
 *   h is written as fp8_e4m3fn with a FIXED scale of 1/448 (h is bounded to [-1,1]),
 *   so no separate per-token quantize kernel is needed; c is updated in-place.
 *
 * Fixed dimension: H={H}  (4H={FH})
 *   h_fp8_out: fp8_e4m3fn bytes [B, {H}]   — output h[t+1] (dequant: byte * (1/448))
 *   c_inout:   f32              [B, {H}]   — cell state, read and overwritten in place
 *   hh:        fp8_e4m3fn bytes [B, {H}]   — input h[t]
 *   scale_hh:  f32              [B]        — per-token input scale (use 1/448 for recurrent h)
 *   w_fused:   fp8_e4m3fn       [{FH_div16}, {H_div16}, 2, 16, 8]  — preshuffled (up @ dn)
 *   scale_wf:  f32              [{FH}]     — per-channel weight scale
 *   bias:      f32              [{FH}]
 *   ih_t:      f16              [B, {H}, 4]  — input-to-hidden, interleaved [B,H,4]
 *
 * Grid:  (B/{tile_m}) * {grid_h}  x 1 x 1   (runtime B)
 * Block: {threads_per_block} x 1 x 1
 */
#pragma once
#include <hip/hip_runtime.h>
#include <stdint.h>
#include <stdio.h>

#define FP8_UNF_LSTM_H                 {H}
#define FP8_UNF_LSTM_FH                {FH}
#define FP8_UNF_LSTM_TILE_M            {tile_m}
#define FP8_UNF_LSTM_TILE_N_H          {tile_n_h}
#define FP8_UNF_LSTM_GRID_H            {grid_h}
#define FP8_UNF_LSTM_THREADS_PER_BLOCK {threads_per_block}
#define FP8_UNF_LSTM_OUT_SCALE         (1.0f / 448.0f)   /* fixed fp8 output scale */

typedef struct {{
    hipModule_t   module;
    hipFunction_t func;
}} fp8_unf_lstm_Module_t;

static inline int fp8_unf_lstm_Module_Load(fp8_unf_lstm_Module_t *m, const char *hsaco_path) {{
    hipError_t err = hipModuleLoad(&m->module, hsaco_path);
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_unf_lstm: hipModuleLoad(%s): %s\\n", hsaco_path, hipGetErrorString(err));
        return (int)err;
    }}
    err = hipModuleGetFunction(&m->func, m->module, "{kernel_name}");
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_unf_lstm: hipModuleGetFunction: %s\\n", hipGetErrorString(err));
        (void)hipModuleUnload(m->module);
        return (int)err;
    }}
    return 0;
}}

static inline void fp8_unf_lstm_Module_Unload(fp8_unf_lstm_Module_t *m) {{
    if (m->module) (void)hipModuleUnload(m->module);
    m->module = NULL;
    m->func   = NULL;
}}

/* Launch the fused unfactored LSTM step.
 * B must be a runtime multiple of FP8_UNF_LSTM_TILE_M; H is fixed at export time.
 * w_fused must be preshuffled fp8 [{FH_div16},{H_div16},2,16,8].
 * h_fp8_out is fp8 with a fixed 1/448 scale; c_inout is updated in place. */
static inline int fp8_unf_lstm_wrapper(
        const fp8_unf_lstm_Module_t *m,
        hipDeviceptr_t d_h_fp8_out,  /* fp8 bytes [B, {H}] */
        hipDeviceptr_t d_c_inout,    /* f32       [B, {H}] */
        hipDeviceptr_t d_hh,         /* fp8 bytes [B, {H}] */
        hipDeviceptr_t d_scale_hh,   /* f32       [B] */
        hipDeviceptr_t d_w_fused,    /* fp8       [{FH_div16},{H_div16},2,16,8] */
        hipDeviceptr_t d_scale_wf,   /* f32       [{FH}] */
        hipDeviceptr_t d_bias,       /* f32       [{FH}] */
        hipDeviceptr_t d_ih_t,       /* f16       [B, {H}, 4] */
        int32_t B,
        hipStream_t stream) {{
    if (B % FP8_UNF_LSTM_TILE_M != 0) {{
        fprintf(stderr, "fp8_unf_lstm: B=%d not divisible by tile_m=%d\\n", B, FP8_UNF_LSTM_TILE_M);
        return -1;
    }}
    int32_t grid_m            = B / FP8_UNF_LSTM_TILE_M;
    unsigned int total_blocks = (unsigned int)grid_m * FP8_UNF_LSTM_GRID_H;
    void *args[] = {{ &d_h_fp8_out, &d_c_inout, &d_hh, &d_scale_hh,
                     &d_w_fused, &d_scale_wf, &d_bias, &d_ih_t, &grid_m }};
    hipError_t err = hipModuleLaunchKernel(
            m->func,
            total_blocks, 1, 1,
            FP8_UNF_LSTM_THREADS_PER_BLOCK, 1, 1,
            0, stream, args, NULL);
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_unf_lstm: hipModuleLaunchKernel: %s\\n", hipGetErrorString(err));
        return (int)err;
    }}
    return 0;
}}
"""


# ── Persistent kernel C header template ──────────────────────────────────────

_HEADER_PERSISTENT = """\
/* Auto-generated by export_fp8_unfactored_lstm.py — do not edit.
 *
 * HSACO ELF for {kernel_name} (gfx1201, wave32/RDNA4).
 *
 * Persistent unfactored LSTM: one kernel launch loops over all T timesteps.
 *   h_fp8_all[0] = initial h; kernel writes h_fp8_all[1..T] in-place.
 *   W_fused (4 MB) stays L2-warm across all T iterations.
 *
 * Fixed dimensions: H={H}  T={T}
 *   h_fp8_all: fp8_e4m3fn uint8 [T+1, B, {H}]  — slot 0 = h[0], slots 1..T = outputs
 *   c_inout:   f32               [B, {H}]       — cell state, read/written in-place
 *   scale_hh:  f32               [B]            — per-token input scale (1/448 for recurrent h)
 *   w_fused:   fp8_e4m3fn        [{FH_div16}, {H_div16}, 2, 16, 8]  — preshuffled
 *   scale_wf:  f32               [{FH}]
 *   bias:      f32               [{FH}]
 *   ih_all:    f16               [T, B, {H}, 4] — all T precomputed ih values
 *
 * Grid:  (B/{tile_m}) * {grid_h}  x 1 x 1   (runtime B)
 * Block: {threads_per_block} x 1 x 1
 */
#pragma once
#include <hip/hip_runtime.h>
#include <stdint.h>
#include <stdio.h>

#define FP8_UNF_LSTM_PERSIST_H                 {H}
#define FP8_UNF_LSTM_PERSIST_FH                {FH}
#define FP8_UNF_LSTM_PERSIST_T                 {T}
#define FP8_UNF_LSTM_PERSIST_TILE_M            {tile_m}
#define FP8_UNF_LSTM_PERSIST_TILE_N_H          {tile_n_h}
#define FP8_UNF_LSTM_PERSIST_GRID_H            {grid_h}
#define FP8_UNF_LSTM_PERSIST_THREADS_PER_BLOCK {threads_per_block}
#define FP8_UNF_LSTM_PERSIST_OUT_SCALE         (1.0f / 448.0f)

typedef struct {{
    hipModule_t   module;
    hipFunction_t func;
}} fp8_unf_lstm_persist_Module_t;

static inline int fp8_unf_lstm_persist_Module_Load(fp8_unf_lstm_persist_Module_t *m, const char *hsaco_path) {{
    hipError_t err = hipModuleLoad(&m->module, hsaco_path);
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_unf_lstm_persist: hipModuleLoad(%s): %s\\n", hsaco_path, hipGetErrorString(err));
        return (int)err;
    }}
    err = hipModuleGetFunction(&m->func, m->module, "{kernel_name}");
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_unf_lstm_persist: hipModuleGetFunction: %s\\n", hipGetErrorString(err));
        (void)hipModuleUnload(m->module);
        return (int)err;
    }}
    return 0;
}}

static inline void fp8_unf_lstm_persist_Module_Unload(fp8_unf_lstm_persist_Module_t *m) {{
    if (m->module) (void)hipModuleUnload(m->module);
    m->module = NULL;
    m->func   = NULL;
}}

/* Launch the persistent unfactored LSTM over all T={T} timesteps.
 * h_fp8_all[0] must be initialised; outputs written to h_fp8_all[1..T].
 * B must be a runtime multiple of FP8_UNF_LSTM_PERSIST_TILE_M.
 * T is baked in at compile time — this wrapper is for T={T} only. */
static inline int fp8_unf_lstm_persistent_wrapper(
        const fp8_unf_lstm_persist_Module_t *m,
        hipDeviceptr_t d_h_fp8_all,  /* fp8 uint8 [T+1, B, {H}] */
        hipDeviceptr_t d_c_inout,    /* f32       [B, {H}] */
        hipDeviceptr_t d_scale_hh,   /* f32       [B] */
        hipDeviceptr_t d_w_fused,    /* fp8       [{FH_div16},{H_div16},2,16,8] */
        hipDeviceptr_t d_scale_wf,   /* f32       [{FH}] */
        hipDeviceptr_t d_bias,       /* f32       [{FH}] */
        hipDeviceptr_t d_ih_all,     /* f16       [T, B, {H}, 4] */
        int32_t B,
        hipStream_t stream) {{
    if (B % FP8_UNF_LSTM_PERSIST_TILE_M != 0) {{
        fprintf(stderr, "fp8_unf_lstm_persist: B=%d not divisible by tile_m=%d\\n",
                B, FP8_UNF_LSTM_PERSIST_TILE_M);
        return -1;
    }}
    int32_t grid_m            = B / FP8_UNF_LSTM_PERSIST_TILE_M;
    unsigned int total_blocks = (unsigned int)grid_m * FP8_UNF_LSTM_PERSIST_GRID_H;
    void *args[] = {{ &d_h_fp8_all, &d_c_inout, &d_scale_hh,
                     &d_w_fused, &d_scale_wf, &d_bias, &d_ih_all, &grid_m }};
    hipError_t err = hipModuleLaunchKernel(
            m->func,
            total_blocks, 1, 1,
            FP8_UNF_LSTM_PERSIST_THREADS_PER_BLOCK, 1, 1,
            0, stream, args, NULL);
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_unf_lstm_persist: hipModuleLaunchKernel: %s\\n", hipGetErrorString(err));
        return (int)err;
    }}
    return 0;
}}
"""


def _compile_and_get_ir_persistent(M: int, H: int, T: int) -> str:
    FH = 4 * H
    launcher    = compile_fp8_unfactored_lstm_gemm_persistent(B=M, H=H, T=T)
    h_fp8_all   = torch.zeros(T + 1, M, H, dtype=torch.uint8)
    c_inout     = torch.zeros(M, H, dtype=torch.float32)
    scale_hh    = torch.zeros(M, dtype=torch.float32)
    w_fused     = torch.zeros(FH // 16, H // 16, 2, 16, 8, dtype=torch.uint8)
    scale_wf    = torch.zeros(FH, dtype=torch.float32)
    bias        = torch.zeros(FH, dtype=torch.float32)
    ih_all      = torch.zeros(T, M, H, 4, dtype=torch.float16)
    prev = os.environ.get("COMPILE_ONLY")
    os.environ["COMPILE_ONLY"] = "1"
    try:
        launcher(h_fp8_all, c_inout, scale_hh, w_fused, scale_wf, bias, ih_all, 0, M)
    finally:
        if prev is None:
            os.environ.pop("COMPILE_ONLY", None)
        else:
            os.environ["COMPILE_ONLY"] = prev
    artifacts = list(launcher._mem_cache.values())
    if not artifacts:
        raise RuntimeError("_mem_cache is empty after persistent-LSTM compilation")
    return artifacts[0]._ir_text


def _export_one_persistent(M: int, H: int, T: int, artifacts_dir: str) -> None:
    FH  = 4 * H
    cfg = _compute_config(M, H)
    name = f"rdna_fp8_unfactored_lstm_persistent_H{H}_T{T}"
    print(f"\n[persistent LSTM M={M}, H={H}, T={T}]  tile_m={cfg['tile_m']}, "
          f"tile_n_h={cfg['tile_n_h']}, threads={cfg['threads_per_block']}, "
          f"blocks={cfg['total_blocks']}")

    ir_text     = _compile_and_get_ir_persistent(M, H, T)
    kernel_name = _find_kernel_name(ir_text)
    print(f"  Kernel: {kernel_name}  IR: {len(ir_text):,} chars")

    hsaco = _extract_hsaco(ir_text, prefer_no_wave64=True)
    if hsaco[:4] != b"\x7fELF":
        raise RuntimeError(f"Expected ELF magic, got: {hsaco[:8].hex()}")

    hsaco_path  = os.path.join(artifacts_dir, f"{name}.hsaco")
    header_path = os.path.join(artifacts_dir, f"{name}.h")
    os.makedirs(artifacts_dir, exist_ok=True)
    with open(hsaco_path, "wb") as f:
        f.write(hsaco)

    header = _HEADER_PERSISTENT.format(
        kernel_name=kernel_name,
        H=H, FH=FH, T=T, FH_div16=FH // 16, H_div16=H // 16,
        tile_m=cfg["tile_m"], tile_n_h=cfg["tile_n_h"],
        grid_h=cfg["grid_h"], threads_per_block=cfg["threads_per_block"],
    )
    _write_text(header_path, header)
    print(f"  Wrote {len(hsaco):,} bytes → {hsaco_path}")
    print(f"  Wrote header → {header_path}")


def _write_text(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)


def _export_one(M: int, H: int, artifacts_dir: str) -> None:
    FH  = 4 * H
    cfg = _compute_config(M, H)
    name = f"rdna_fp8_unfactored_lstm_H{H}"
    print(f"\n[unfactored LSTM M={M}, H={H}, 4H={FH}]  tile_m={cfg['tile_m']}, "
          f"tile_n_h={cfg['tile_n_h']}, threads={cfg['threads_per_block']}, "
          f"blocks={cfg['total_blocks']}")

    ir_text     = _compile_and_get_ir(M, H)
    kernel_name = _find_kernel_name(ir_text)
    print(f"  Kernel: {kernel_name}  IR: {len(ir_text):,} chars")

    hsaco = _extract_hsaco(ir_text, prefer_no_wave64=True)
    if hsaco[:4] != b"\x7fELF":
        raise RuntimeError(f"Expected ELF magic, got: {hsaco[:8].hex()}")

    hsaco_path  = os.path.join(artifacts_dir, f"{name}.hsaco")
    header_path = os.path.join(artifacts_dir, f"{name}.h")
    os.makedirs(artifacts_dir, exist_ok=True)
    with open(hsaco_path, "wb") as f:
        f.write(hsaco)

    header = _HEADER.format(
        kernel_name=kernel_name,
        H=H, FH=FH, FH_div16=FH // 16, H_div16=H // 16,
        tile_m=cfg["tile_m"], tile_n_h=cfg["tile_n_h"],
        grid_h=cfg["grid_h"], threads_per_block=cfg["threads_per_block"],
    )
    _write_text(header_path, header)
    print(f"  Wrote {len(hsaco):,} bytes → {hsaco_path}")
    print(f"  Wrote header → {header_path}")


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Export the fused unfactored fp8 LSTM kernel as HSACO + C header."
    )
    parser.add_argument("--config", metavar="FILE",
                        help="TOML config file with a list of M,H configs to batch-export")
    parser.add_argument("--M", type=int, default=512, help="Batch dimension (runtime; default: 512)")
    parser.add_argument("--H", type=int, default=1024, help="Hidden dimension (default: 1024)")
    parser.add_argument("--persistent", action="store_true",
                        help="Export the persistent kernel (all T timesteps in one launch)")
    parser.add_argument("--T", type=int, default=1024,
                        help="Sequence length for persistent kernel (default: 1024)")
    args = parser.parse_args()

    artifacts_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "artifacts")

    if args.persistent:
        _export_one_persistent(args.M, args.H, args.T, artifacts_dir)
    elif args.config:
        configs = _load_configs(args.config, default_m=args.M)
        print(f"Batch export: {len(configs)} config(s) from {args.config}")
        for M, H in configs:
            _export_one(M, H, artifacts_dir)
        print(f"\nDone. {len(configs)} config(s) exported to {artifacts_dir}/")
    else:
        _export_one(args.M, args.H, artifacts_dir)
