"""Export rdna_fp8_preshuffle_gemm as a self-contained C header with embedded HSACO.

Configuration: M=32, N=8192, K=6144 (decode-phase inference default).

Run with:
    python export_fp8_gemm.py

Outputs:
    artifacts/rdna_fp8_gemm.h
"""
import os
import re
import sys

os.environ.setdefault("FLYDSL_RUNTIME_ENABLE_CACHE", "0")

import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fly.rdna_fp8_preshuffle_gemm import compile_fp8_gemm

# ── Shape ─────────────────────────────────────────────────────────────────────
M, N, K = 32, 8192, 6144

# These reproduce the auto-selection logic inside compile_fp8_gemm for M=32:
#   tile_n = 128  (M < 256)
#   k_unroll = 2  (M < 256)
#   waves_m = 1, waves_n = 2  (tile_n >= 128 and tile_m < 64)
TILE_M, TILE_N = 32, 128
WAVES_M, WAVES_N = 1, 2
THREADS_PER_BLOCK = WAVES_M * WAVES_N * 32   # = 64
TOTAL_BLOCKS = (M // TILE_M) * (N // TILE_N)  # = 64


# ── Compilation ───────────────────────────────────────────────────────────────

def _compile_and_get_ir():
    launcher = compile_fp8_gemm(M=M, N=N, K=K)

    # Dummy tensors to trigger JIT — shapes/dtypes must match what the kernel
    # expects from buffer_ops (raw byte access), so dtype only affects cache key.
    C       = torch.zeros(M, N, dtype=torch.bfloat16).cuda()
    A       = torch.zeros(M, K, dtype=torch.uint8).cuda()     # fp8 stored as u8
    B_shuf  = torch.zeros(N // 16, K // 16, 2, 16, 8, dtype=torch.uint8).cuda()
    scale_a = torch.ones(M, dtype=torch.float32).cuda()
    scale_b = torch.ones(N, dtype=torch.float32).cuda()
    stream  = torch.cuda.current_stream()

    launcher(C, A, B_shuf, scale_a, scale_b, stream)
    torch.cuda.synchronize()

    artifacts = list(launcher._mem_cache.values())
    if not artifacts:
        raise RuntimeError("_mem_cache is empty after compilation")
    return artifacts[0]._ir_text


# ── MLIR string decoding (same as export_vec_add.py) ─────────────────────────

def _decode_mlir_bin(ir_text: str, start: int) -> bytes:
    marker = 'bin = "'
    pos = ir_text.find(marker, start)
    if pos == -1:
        raise ValueError("'bin = \"' not found in IR text after position %d" % start)
    i = pos + len(marker)
    result = bytearray()
    while i < len(ir_text):
        c = ir_text[i]
        if c == '\\':
            nxt = ir_text[i + 1]
            if nxt == '\\':
                result.append(ord('\\'))
                i += 2
            elif nxt == '"':
                result.append(ord('"'))
                i += 2
            else:
                result.append(int(ir_text[i + 1: i + 3], 16))
                i += 3
        elif c == '"':
            break
        else:
            result.append(ord(c))
            i += 1
    return bytes(result)


def _extract_hsaco(ir_text: str, prefer_no_wave64: bool = True) -> bytes:
    if prefer_no_wave64:
        anchor = ir_text.find("no_wave64")
        if anchor == -1:
            print("Warning: no_wave64 variant not found, falling back to first object")
            anchor = 0
    else:
        anchor = 0
    return _decode_mlir_bin(ir_text, anchor)


def _find_kernel_name(ir_text: str) -> str:
    m = re.search(r'#gpu\.kernel_metadata<"([^"]+)"', ir_text)
    return m.group(1) if m else "kernel_gemm_0"


# ── C header template ─────────────────────────────────────────────────────────

_HEADER_TEMPLATE = """\
/* Auto-generated by export_fp8_gemm.py — do not edit.
 *
 * HSACO ELF for {kernel_name} (gfx1201, wave32/RDNA4).
 *
 * Computes:  C[M,N] = (A[M,K] @ B[K,N]) * scale_a[M,1] * scale_b[1,N]
 * where A and B are fp8_e4m3fn, output C is bf16.
 *
 * Fixed dimensions: M={M}, N={N}, K={K}
 *   A:       fp8_e4m3fn  [{M}, {K}]         — raw row-major
 *   B:       fp8_e4m3fn  [{N}//16, {K}//16, 2, 16, 8]  — preshuffled (see below)
 *   C:       bf16        [{M}, {N}]         — output
 *   scale_a: f32         [{M}]              — per-token (per-row) activation scale
 *   scale_b: f32         [{N}]              — per-channel weight scale
 *
 * B must be preshuffled before calling the kernel.
 * C++ preshuffle: see preshuffle_b() in main_rdna_fp8_gemm.cpp
 * Python preshuffle: fly.rdna_fp8_preshuffle_gemm.preshuffle_b_fp8
 *
 * Grid:  {total_blocks} x 1 x 1
 * Block: {threads_per_block} x 1 x 1
 *
 * Build: hipcc -o main_rdna_fp8_gemm main_rdna_fp8_gemm.cpp
 */
#pragma once
#include <hip/hip_runtime.h>
#include <stdint.h>
#include <stdio.h>

/* ── Embedded HSACO binary ({size} bytes) ── */
static const uint8_t fp8_gemm_hsaco[] = {{
{hex_array}
}};
static const size_t fp8_gemm_hsaco_size = {size}UL;

/* ── Module handle ── */
typedef struct {{
    hipModule_t   module;
    hipFunction_t func;
}} fp8_gemm_Module_t;

static inline int fp8_gemm_Module_Load(fp8_gemm_Module_t *m) {{
    hipError_t err = hipModuleLoadData(&m->module, fp8_gemm_hsaco);
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_gemm: hipModuleLoadData: %s\\n", hipGetErrorString(err));
        return (int)err;
    }}
    err = hipModuleGetFunction(&m->func, m->module, "{kernel_name}");
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_gemm: hipModuleGetFunction: %s\\n", hipGetErrorString(err));
        (void)hipModuleUnload(m->module);
        return (int)err;
    }}
    return 0;
}}

static inline void fp8_gemm_Module_Unload(fp8_gemm_Module_t *m) {{
    if (m->module) (void)hipModuleUnload(m->module);
    m->module = NULL;
    m->func   = NULL;
}}

/* Launch the kernel.
 * All device pointers must point to contiguous row-major device memory.
 * d_B_shuf must already be in preshuffled layout [{N_div16},{K_div16},2,16,8].
 * Returns 0 on success, non-zero HIP error code otherwise. */
static inline int fp8_gemm_wrapper(
        const fp8_gemm_Module_t *m,
        hipDeviceptr_t d_C,       /* bf16  [{M},{N}] */
        hipDeviceptr_t d_A,       /* fp8   [{M},{K}] */
        hipDeviceptr_t d_B_shuf,  /* fp8   [{N_div16},{K_div16},2,16,8] */
        hipDeviceptr_t d_scale_a, /* f32   [{M}] */
        hipDeviceptr_t d_scale_b, /* f32   [{N}] */
        hipStream_t stream) {{
    void *args[] = {{ &d_C, &d_A, &d_B_shuf, &d_scale_a, &d_scale_b }};
    hipError_t err = hipModuleLaunchKernel(
            m->func,
            {total_blocks}, 1, 1,        /* grid  */
            {threads_per_block}, 1, 1,   /* block */
            0, stream, args, NULL);
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_gemm: hipModuleLaunchKernel: %s\\n", hipGetErrorString(err));
        return (int)err;
    }}
    return 0;
}}
"""

_BYTES_PER_LINE = 16


def _format_hex(data: bytes) -> str:
    lines = []
    for off in range(0, len(data), _BYTES_PER_LINE):
        chunk = data[off: off + _BYTES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
    return ",\n".join(lines)


def _generate_header(hsaco: bytes, kernel_name: str, output_path: str) -> None:
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    content = _HEADER_TEMPLATE.format(
        kernel_name=kernel_name,
        M=M, N=N, K=K,
        N_div16=N // 16, K_div16=K // 16,
        total_blocks=TOTAL_BLOCKS,
        threads_per_block=THREADS_PER_BLOCK,
        size=len(hsaco),
        hex_array=_format_hex(hsaco),
    )
    with open(output_path, "w") as f:
        f.write(content)
    print(f"Wrote {len(hsaco):,} bytes of HSACO to {output_path}")


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print(f"Compiling fp8 GEMM kernel (M={M}, N={N}, K={K})...")
    ir_text = _compile_and_get_ir()
    print(f"Compiled IR text: {len(ir_text):,} chars")

    kernel_name = _find_kernel_name(ir_text)
    print(f"Kernel name: {kernel_name}")

    print("Extracting HSACO (wave32 / no_wave64 variant)...")
    hsaco = _extract_hsaco(ir_text, prefer_no_wave64=True)
    print(f"Extracted HSACO: {len(hsaco):,} bytes")

    if hsaco[:4] != b"\x7fELF":
        raise RuntimeError(f"Expected ELF magic, got: {hsaco[:8].hex()}")
    print("ELF magic verified.")

    output = os.path.join(os.path.dirname(os.path.abspath(__file__)), "artifacts", "rdna_fp8_gemm.h")
    _generate_header(hsaco, kernel_name, output)
