"""Export rdna_fp8_factored_gemm as HSACO + C header.

Single fused dispatch: ih[M,N] = (x_fp8 @ dn_fp8) @ up_f16 + bias  — the low-rank
input projection (down-proj fp8 → x_down f16 in LDS → up-proj f16 → bias → f16).

Run with:
    python fly/export_fp8_factored_gemm.py                                # defaults
    python fly/export_fp8_factored_gemm.py --C 1024 --R 128 --N 4096      # single config
    python fly/export_fp8_factored_gemm.py --config fly/export_configs/rdna_fp8_factored_gemm.toml

Outputs per config (in fly/artifacts/):
    rdna_fp8_factored_gemm_C{C}_R{R}_N{N}.hsaco + .h
"""
import argparse
import os
import re
import sys

try:
    import tomllib
except ModuleNotFoundError:
    try:
        import tomli as tomllib  # type: ignore[no-redef]
    except ModuleNotFoundError:
        tomllib = None  # type: ignore[assignment]

os.environ.setdefault("FLYDSL_RUNTIME_ENABLE_CACHE", "0")

import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rdna_fp8_factored_gemm import compile_fp8_factored_gemm

TILE_M  = 32
TILE_N2 = 128
THREADS_PER_BLOCK = 64   # waves_m=1 * waves_n=2 * 32


def _load_configs(path: str, default_m: int = 512):
    if tomllib is None:
        raise RuntimeError("tomllib not available — upgrade to Python 3.11+ or `pip install tomli`")
    with open(path, "rb") as f:
        data = tomllib.load(f)
    return [(int(c.get("M", default_m)), int(c["C"]), int(c["R"]), int(c["N"]),
             int(c.get("n_split", 1))) for c in data["configs"]]


def _compile_and_get_ir(M: int, C: int, R: int, N: int, n_split: int) -> str:
    launcher    = compile_fp8_factored_gemm(C=C, R=R, N=N, n_split=n_split)
    ih_out      = torch.zeros(M, N, dtype=torch.float16)
    x           = torch.zeros(M, C, dtype=torch.uint8)
    scale_x     = torch.zeros(M, dtype=torch.float32)
    dn_weight   = torch.zeros(R // 16, C // 16, 2, 16, 8, dtype=torch.uint8)   # preshuffled fp8
    scale_dn    = torch.zeros(1, dtype=torch.float32)
    up_weight   = torch.zeros(N // 16, R // 16, 2, 16, 8, dtype=torch.float16) # preshuffled f16
    bias        = torch.zeros(N, dtype=torch.float32)
    prev = os.environ.get("COMPILE_ONLY")
    os.environ["COMPILE_ONLY"] = "1"
    try:
        launcher(ih_out, x, scale_x, dn_weight, scale_dn, up_weight, bias, 0, M)
    finally:
        if prev is None:
            os.environ.pop("COMPILE_ONLY", None)
        else:
            os.environ["COMPILE_ONLY"] = prev
    artifacts = list(launcher._mem_cache.values())
    if not artifacts:
        raise RuntimeError("_mem_cache is empty after factored-GEMM compilation")
    return artifacts[0]._ir_text


def _decode_mlir_bin(ir_text: str, start: int) -> bytes:
    marker = 'bin = "'
    pos = ir_text.find(marker, start)
    if pos == -1:
        raise ValueError("'bin = \"' not found in IR text after position %d" % start)
    i = pos + len(marker)
    result = bytearray()
    while i < len(ir_text):
        c = ir_text[i]
        if c == '\\':
            nxt = ir_text[i + 1]
            if nxt == '\\':
                result.append(ord('\\')); i += 2
            elif nxt == '"':
                result.append(ord('"')); i += 2
            else:
                result.append(int(ir_text[i + 1: i + 3], 16)); i += 3
        elif c == '"':
            break
        else:
            result.append(ord(c)); i += 1
    return bytes(result)


def _extract_hsaco(ir_text: str, prefer_no_wave64: bool = True) -> bytes:
    if prefer_no_wave64:
        anchor = ir_text.find("no_wave64")
        if anchor == -1:
            print("Warning: no_wave64 variant not found, falling back to first object")
            anchor = 0
    else:
        anchor = 0
    return _decode_mlir_bin(ir_text, anchor)


def _find_kernel_name(ir_text: str) -> str:
    m = re.search(r'#gpu\.kernel_metadata<"([^"]+)"', ir_text)
    return m.group(1) if m else "kernel_0"


_HEADER = """\
/* Auto-generated by export_fp8_factored_gemm.py — do not edit.
 *
 * HSACO ELF for {kernel_name} (gfx1201, wave32/RDNA4).
 *
 * Fused low-rank ("factored") GEMM input projection (single dispatch):
 *   x_down = x_fp8[M,C] @ dn_fp8[C,R]    (descale: x per-token * dn scalar) -> f16 in LDS
 *   ih     = x_down_f16[M,R] @ up_f16[R,N] + bias[N]  -> f16 output
 * The M*R intermediate stays in LDS (no global round-trip).
 *
 * Fixed dims: C={C}, R={R}, N={N}   (M is runtime)
 *   ih_out:   f16              [M, {N}]                       — output
 *   x:        fp8_e4m3fn bytes [M, {C}]                       — input activation
 *   scale_x:  f32              [M]                            — per-token scale for x
 *   dn_w:     fp8_e4m3fn       [{R_div16}, {C_div16}, 2, 16, 8]  — preshuffled (dn^T, [C,R])
 *   scale_dn: f32              [1]                            — scalar scale for dn
 *   up_w:     f16              [{N_div16}, {R_div16}, 2, 16, 8]  — preshuffled (up^T, [R,N])
 *   bias:     f32              [{N}]
 *
 * up_w columns must be pre-permuted to the desired output column order
 * (e.g. interleaved [.,H,4]); this kernel writes ih[M,N] row-major.
 *
 * Grid:  (M/{tile_m}) x 1 x 1   (runtime M)
 * Block: {threads_per_block} x 1 x 1
 */
#pragma once
#include <hip/hip_runtime.h>
#include <stdint.h>
#include <stdio.h>

#define FP8_FAC_GEMM_C                 {C}
#define FP8_FAC_GEMM_R                 {R}
#define FP8_FAC_GEMM_N                 {N}
#define FP8_FAC_GEMM_TILE_M            {tile_m}
#define FP8_FAC_GEMM_N_SPLIT           {n_split}
#define FP8_FAC_GEMM_THREADS_PER_BLOCK {threads_per_block}

typedef struct {{
    hipModule_t   module;
    hipFunction_t func;
}} fp8_fac_gemm_Module_t;

static inline int fp8_fac_gemm_Module_Load(fp8_fac_gemm_Module_t *m, const char *hsaco_path) {{
    hipError_t err = hipModuleLoad(&m->module, hsaco_path);
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_fac_gemm: hipModuleLoad(%s): %s\\n", hsaco_path, hipGetErrorString(err));
        return (int)err;
    }}
    err = hipModuleGetFunction(&m->func, m->module, "{kernel_name}");
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_fac_gemm: hipModuleGetFunction: %s\\n", hipGetErrorString(err));
        (void)hipModuleUnload(m->module);
        return (int)err;
    }}
    return 0;
}}

static inline void fp8_fac_gemm_Module_Unload(fp8_fac_gemm_Module_t *m) {{
    if (m->module) (void)hipModuleUnload(m->module);
    m->module = NULL;
    m->func   = NULL;
}}

/* Launch the fused factored GEMM.
 * M must be a runtime multiple of FP8_FAC_GEMM_TILE_M; C,R,N are fixed at export time.
 * dn_w preshuffled fp8 [{R_div16},{C_div16},2,16,8]; up_w preshuffled f16 [{N_div16},{R_div16},2,16,8]. */
static inline int fp8_fac_gemm_wrapper(
        const fp8_fac_gemm_Module_t *m,
        hipDeviceptr_t d_ih_out,    /* f16       [M, {N}] */
        hipDeviceptr_t d_x,         /* fp8 bytes [M, {C}] */
        hipDeviceptr_t d_scale_x,   /* f32       [M] */
        hipDeviceptr_t d_dn_w,      /* fp8       [{R_div16},{C_div16},2,16,8] */
        hipDeviceptr_t d_scale_dn,  /* f32       [1] */
        hipDeviceptr_t d_up_w,      /* f16       [{N_div16},{R_div16},2,16,8] */
        hipDeviceptr_t d_bias,      /* f32       [{N}] */
        int32_t M,             /* row count; ANY value — tail (M % tile_m) handled internally */
        hipStream_t stream) {{
    /* ceil(M/tile_m) M-tiles, each split into N_SPLIT N-chunk blocks (raises occupancy at
     * small M). The kernel masks rows >= M, so M need NOT be a multiple of tile_m. */
    int32_t grid_m       = (M + (FP8_FAC_GEMM_TILE_M - 1)) / FP8_FAC_GEMM_TILE_M;
    unsigned int blocks  = (unsigned int)grid_m * FP8_FAC_GEMM_N_SPLIT;
    void *args[] = {{ &d_ih_out, &d_x, &d_scale_x, &d_dn_w, &d_scale_dn,
                     &d_up_w, &d_bias, &M }};
    hipError_t err = hipModuleLaunchKernel(
            m->func,
            blocks, 1, 1,
            FP8_FAC_GEMM_THREADS_PER_BLOCK, 1, 1,
            0, stream, args, NULL);
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_fac_gemm: hipModuleLaunchKernel: %s\\n", hipGetErrorString(err));
        return (int)err;
    }}
    return 0;
}}
"""


def _write_text(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)


def _export_one(M: int, C: int, R: int, N: int, n_split: int, artifacts_dir: str) -> None:
    name = f"rdna_fp8_factored_gemm_C{C}_R{R}_N{N}"
    print(f"\n[factored GEMM M={M}, C={C}, R={R}, N={N}]  tile_m={TILE_M}, "
          f"tile_n2={TILE_N2}, n_split={n_split}, threads={THREADS_PER_BLOCK}, "
          f"blocks=ceil(M/{TILE_M})*{n_split}")

    ir_text     = _compile_and_get_ir(M, C, R, N, n_split)
    kernel_name = _find_kernel_name(ir_text)
    print(f"  Kernel: {kernel_name}  IR: {len(ir_text):,} chars")

    hsaco = _extract_hsaco(ir_text, prefer_no_wave64=True)
    if hsaco[:4] != b"\x7fELF":
        raise RuntimeError(f"Expected ELF magic, got: {hsaco[:8].hex()}")

    hsaco_path  = os.path.join(artifacts_dir, f"{name}.hsaco")
    header_path = os.path.join(artifacts_dir, f"{name}.h")
    os.makedirs(artifacts_dir, exist_ok=True)
    with open(hsaco_path, "wb") as f:
        f.write(hsaco)

    header = _HEADER.format(
        kernel_name=kernel_name, C=C, R=R, N=N,
        C_div16=C // 16, R_div16=R // 16, N_div16=N // 16,
        tile_m=TILE_M, n_split=n_split, threads_per_block=THREADS_PER_BLOCK,
    )
    _write_text(header_path, header)
    print(f"  Wrote {len(hsaco):,} bytes → {hsaco_path}")
    print(f"  Wrote header → {header_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Export the fused fp8 low-rank GEMM (input projection) as HSACO + C header."
    )
    parser.add_argument("--config", metavar="FILE",
                        help="TOML config file with a list of M,C,R,N configs to batch-export")
    parser.add_argument("--M", type=int, default=512, help="Batch dim (runtime; default: 512)")
    parser.add_argument("--C", type=int, default=1024, help="Input feature dim (default: 1024)")
    parser.add_argument("--R", type=int, default=128,  help="Rank / intermediate dim (default: 128)")
    parser.add_argument("--N", type=int, default=4096, help="Output dim (default: 4096)")
    parser.add_argument("--n_split", type=int, default=1,
                        help="split N across this many blocks/M-tile (use ~128/ceil(M/32) for small M)")
    args = parser.parse_args()

    artifacts_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "artifacts")

    if args.config:
        configs = _load_configs(args.config, default_m=args.M)
        print(f"Batch export: {len(configs)} config(s) from {args.config}")
        for M, C, R, N, n_split in configs:
            _export_one(M, C, R, N, n_split, artifacts_dir)
        print(f"\nDone. {len(configs)} config(s) exported to {artifacts_dir}/")
    else:
        _export_one(args.M, args.C, args.R, args.N, args.n_split, artifacts_dir)
