"""Export rdna_fp8_fused_lstm (compile_fp8_fused_lstm) as HSACO + C header.

Single fused dispatch — folds the input up-projection into the LSTM gates:
  gates = hh_fp8 @ W_fused_fp8 (descaled) + x_down_f16 @ up_ih_f16 + bias_hh + bias_ih
  i,f,o = sighard; g = tanh_hard; c = f*c + i*g; h = o*tanh(c) -> fp8 (1/448)
No ih[B,4H] tensor — reads the tiny x_down[B,R] (= x @ dn, precomputed) instead.

Run:
    python fly/export_fp8_fused_lstm.py
    python fly/export_fp8_fused_lstm.py --config fly/export_configs/rdna_fp8_fused_lstm.toml

Output: artifacts/rdna_fp8_fused_lstm_H{H}_R{R}.hsaco + .h
"""
import argparse
import os
import re
import sys

try:
    import tomllib
except ModuleNotFoundError:
    try:
        import tomli as tomllib  # type: ignore[no-redef]
    except ModuleNotFoundError:
        tomllib = None  # type: ignore[assignment]

os.environ.setdefault("FLYDSL_RUNTIME_ENABLE_CACHE", "0")

import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rdna_fp8_unfactored_lstm_gemm import compile_fp8_fused_lstm

TILE_M = 32
TILE_N_H = 32
THREADS_PER_BLOCK = 64   # waves 1x2


def _load_configs(path, default_m=256):
    if tomllib is None:
        raise RuntimeError("tomllib not available — Python 3.11+ or `pip install tomli`")
    with open(path, "rb") as f:
        data = tomllib.load(f)
    return [(int(c.get("M", default_m)), int(c["H"]), int(c["R"])) for c in data["configs"]]


def _compile_and_get_ir(M, H, R):
    FH = 4 * H
    launcher   = compile_fp8_fused_lstm(B=M, H=H, R=R)
    h_fp8_out  = torch.zeros(M, H, dtype=torch.uint8)
    c_inout    = torch.zeros(M, H, dtype=torch.float32)
    hh         = torch.zeros(M, H, dtype=torch.uint8)
    scale_hh   = torch.zeros(M, dtype=torch.float32)
    w_fused    = torch.zeros(FH // 16, H // 16, 2, 16, 8, dtype=torch.uint8)
    scale_wf   = torch.zeros(FH, dtype=torch.float32)
    bias_hh    = torch.zeros(FH, dtype=torch.float32)
    x_down     = torch.zeros(M, R, dtype=torch.float16)
    up_ih      = torch.zeros(FH // 16, R // 16, 2, 16, 8, dtype=torch.float16)
    bias_ih    = torch.zeros(FH, dtype=torch.float32)
    prev = os.environ.get("COMPILE_ONLY")
    os.environ["COMPILE_ONLY"] = "1"
    try:
        launcher(h_fp8_out, c_inout, hh, scale_hh, w_fused, scale_wf, bias_hh,
                 x_down, up_ih, bias_ih, 0, M)
    finally:
        if prev is None: os.environ.pop("COMPILE_ONLY", None)
        else:            os.environ["COMPILE_ONLY"] = prev
    arts = list(launcher._mem_cache.values())
    if not arts:
        raise RuntimeError("_mem_cache empty after fused-LSTM compilation")
    return arts[0]._ir_text


def _decode_mlir_bin(ir_text, start):
    marker = 'bin = "'
    pos = ir_text.find(marker, start)
    if pos == -1:
        raise ValueError("'bin = \"' not found")
    i = pos + len(marker); out = bytearray()
    while i < len(ir_text):
        ch = ir_text[i]
        if ch == '\\':
            nxt = ir_text[i + 1]
            if nxt == '\\': out.append(0x5C); i += 2
            elif nxt == '"': out.append(0x22); i += 2
            else: out.append(int(ir_text[i + 1:i + 3], 16)); i += 3
        elif ch == '"': break
        else: out.append(ord(ch)); i += 1
    return bytes(out)


def _extract_hsaco(ir_text):
    a = ir_text.find("no_wave64")
    if a == -1:
        print("Warning: no_wave64 not found, using first object"); a = 0
    return _decode_mlir_bin(ir_text, a)


def _find_kernel_name(ir_text):
    m = re.search(r'#gpu\.kernel_metadata<"([^"]+)"', ir_text)
    return m.group(1) if m else "kernel_0"


_HEADER = """\
/* Auto-generated by export_fp8_fused_lstm.py — do not edit.
 *
 * HSACO ELF for {kernel_name} (gfx1201, wave32/RDNA4).
 *
 * Fused LSTM step (single dispatch) — input up-projection folded into the gates:
 *   gates = hh_fp8 @ W_fused_fp8 (descaled by scale_hh*scale_wf)
 *         + x_down_f16 @ up_ih_f16 + bias_hh + bias_ih
 *   i,f,o = clamp(0.2*x+0.5,0,1); g = clamp(x,-1,1); c = f*c + i*g; h = o*tanh(c)
 *   h -> fp8_e4m3fn, FIXED scale 1/448 (dequant: byte * 1/448); c updated in place.
 *   No ih[B,4H] tensor — reads x_down[B,R] (= x @ dn) instead.
 *
 * Fixed dims: H={H}, R={R}  (4H={FH})
 *   h_fp8_out: fp8 bytes [B, {H}]
 *   c_inout:   f32        [B, {H}]   (read+written in place)
 *   hh:        fp8 bytes  [B, {H}]
 *   scale_hh:  f32        [B]
 *   w_fused:   fp8        [{FH_div16}, {H_div16}, 2, 16, 8]  preshuffled (up_hh @ dn_hh)
 *   scale_wf:  f32        [{FH}]     per-channel
 *   bias_hh:   f32        [{FH}]
 *   x_down:    f16        [B, {R}]   (= x @ dn_ih, precomputed; row-major)
 *   up_ih:     f16        [{FH_div16}, {R_div16}, 2, 16, 8]  preshuffled, gate-major [4H,R]
 *   bias_ih:   f32        [{FH}]
 *
 * Grid:  (B/{tile_m}) * {grid_h}  x 1 x 1   (runtime B; grid_h = H/{tile_n_h})
 * Block: {threads_per_block} x 1 x 1
 */
#pragma once
#include <hip/hip_runtime.h>
#include <stdint.h>
#include <stdio.h>

#define FP8_FUSED_LSTM_H                 {H}
#define FP8_FUSED_LSTM_R                 {R}
#define FP8_FUSED_LSTM_FH                {FH}
#define FP8_FUSED_LSTM_TILE_M            {tile_m}
#define FP8_FUSED_LSTM_GRID_H            {grid_h}
#define FP8_FUSED_LSTM_THREADS_PER_BLOCK {threads_per_block}
#define FP8_FUSED_LSTM_OUT_SCALE         (1.0f / 448.0f)

typedef struct {{ hipModule_t module; hipFunction_t func; }} fp8_fused_lstm_Module_t;

static inline int fp8_fused_lstm_Module_Load(fp8_fused_lstm_Module_t *m, const char *hsaco_path) {{
    hipError_t err = hipModuleLoad(&m->module, hsaco_path);
    if (err != hipSuccess) {{ fprintf(stderr, "fp8_fused_lstm: hipModuleLoad(%s): %s\\n", hsaco_path, hipGetErrorString(err)); return (int)err; }}
    err = hipModuleGetFunction(&m->func, m->module, "{kernel_name}");
    if (err != hipSuccess) {{ fprintf(stderr, "fp8_fused_lstm: hipModuleGetFunction: %s\\n", hipGetErrorString(err)); (void)hipModuleUnload(m->module); return (int)err; }}
    return 0;
}}

static inline void fp8_fused_lstm_Module_Unload(fp8_fused_lstm_Module_t *m) {{
    if (m->module) (void)hipModuleUnload(m->module);
    m->module = NULL; m->func = NULL;
}}

/* Launch the fused LSTM step. B must be a runtime multiple of FP8_FUSED_LSTM_TILE_M. */
static inline int fp8_fused_lstm_wrapper(
        const fp8_fused_lstm_Module_t *m,
        hipDeviceptr_t d_h_fp8_out,  /* fp8 [B,{H}] */
        hipDeviceptr_t d_c_inout,    /* f32 [B,{H}] */
        hipDeviceptr_t d_hh,         /* fp8 [B,{H}] */
        hipDeviceptr_t d_scale_hh,   /* f32 [B] */
        hipDeviceptr_t d_w_fused,    /* fp8 [{FH_div16},{H_div16},2,16,8] */
        hipDeviceptr_t d_scale_wf,   /* f32 [{FH}] */
        hipDeviceptr_t d_bias_hh,    /* f32 [{FH}] */
        hipDeviceptr_t d_x_down,     /* f16 [B,{R}] */
        hipDeviceptr_t d_up_ih,      /* f16 [{FH_div16},{R_div16},2,16,8] */
        hipDeviceptr_t d_bias_ih,    /* f32 [{FH}] */
        int32_t B,
        hipStream_t stream) {{
    if (B % FP8_FUSED_LSTM_TILE_M != 0) {{
        fprintf(stderr, "fp8_fused_lstm: B=%d not divisible by tile_m=%d\\n", B, FP8_FUSED_LSTM_TILE_M);
        return -1;
    }}
    int32_t grid_m            = B / FP8_FUSED_LSTM_TILE_M;
    unsigned int total_blocks = (unsigned int)grid_m * FP8_FUSED_LSTM_GRID_H;
    void *args[] = {{ &d_h_fp8_out, &d_c_inout, &d_hh, &d_scale_hh, &d_w_fused, &d_scale_wf,
                     &d_bias_hh, &d_x_down, &d_up_ih, &d_bias_ih, &grid_m }};
    hipError_t err = hipModuleLaunchKernel(m->func, total_blocks, 1, 1,
            FP8_FUSED_LSTM_THREADS_PER_BLOCK, 1, 1, 0, stream, args, NULL);
    if (err != hipSuccess) {{ fprintf(stderr, "fp8_fused_lstm: launch: %s\\n", hipGetErrorString(err)); return (int)err; }}
    return 0;
}}
"""


def _write_text(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)


def _export_one(M, H, R, artifacts_dir):
    FH = 4 * H
    grid_h = H // TILE_N_H
    name = f"rdna_fp8_fused_lstm_H{H}_R{R}"
    print(f"\n[fused LSTM M={M}, H={H}, R={R}]  tile_m={TILE_M}, grid_h={grid_h}, "
          f"threads={THREADS_PER_BLOCK}, blocks=(B/{TILE_M})*{grid_h}")
    ir_text = _compile_and_get_ir(M, H, R)
    kernel_name = _find_kernel_name(ir_text)
    print(f"  Kernel: {kernel_name}  IR: {len(ir_text):,} chars")
    hsaco = _extract_hsaco(ir_text)
    if hsaco[:4] != b"\x7fELF":
        raise RuntimeError(f"Expected ELF magic, got {hsaco[:8].hex()}")
    hsaco_path  = os.path.join(artifacts_dir, f"{name}.hsaco")
    header_path = os.path.join(artifacts_dir, f"{name}.h")
    os.makedirs(artifacts_dir, exist_ok=True)
    with open(hsaco_path, "wb") as f:
        f.write(hsaco)
    _write_text(header_path, _HEADER.format(
        kernel_name=kernel_name, H=H, R=R, FH=FH,
        FH_div16=FH // 16, H_div16=H // 16, R_div16=R // 16,
        tile_m=TILE_M, tile_n_h=TILE_N_H, grid_h=grid_h, threads_per_block=THREADS_PER_BLOCK))
    print(f"  Wrote {len(hsaco):,} bytes → {hsaco_path}")
    print(f"  Wrote header → {header_path}")


if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Export fused LSTM kernel as HSACO + C header.")
    p.add_argument("--config", metavar="FILE")
    p.add_argument("--M", type=int, default=256)
    p.add_argument("--H", type=int, default=1024)
    p.add_argument("--R", type=int, default=128)
    args = p.parse_args()
    artifacts_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "artifacts")
    if args.config:
        cfgs = _load_configs(args.config, default_m=args.M)
        print(f"Batch export: {len(cfgs)} config(s) from {args.config}")
        for M, H, R in cfgs:
            _export_one(M, H, R, artifacts_dir)
        print(f"\nDone. {len(cfgs)} config(s) → {artifacts_dir}/")
    else:
        _export_one(args.M, args.H, args.R, artifacts_dir)
