"""Export rdna_f16_down_proj (compile_f16_down_proj) as HSACO + C header.

x_down[M,R] f16 = x[M,C]_f16 @ dn[C,R]_f16  — NO quantization, no scales.
Replaces (fp8 quantize + fp8 down_proj) for the LAYER-0 precompute, where the input x
is f16: reads x directly, killing the whole quantize pass. The precompute is
bandwidth-bound, so f16 WMMA costs nothing vs fp8, and x_down is more accurate.

Run:
    python fly/export_f16_down_proj.py --config fly/export_configs/rdna_f16_down_proj.toml

Output: artifacts/rdna_f16_down_proj_C{C}_R{R}.hsaco + .h
"""
import argparse, os, re, sys
try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib  # type: ignore

os.environ.setdefault("FLYDSL_RUNTIME_ENABLE_CACHE", "0")
import torch
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rdna_fp8_factored_gemm import compile_f16_down_proj

TILE_M = 32
THREADS_PER_BLOCK = 64


def _load_configs(path, default_m=256):
    with open(path, "rb") as f:
        data = tomllib.load(f)
    return [(int(c.get("M", default_m)), int(c["C"]), int(c["R"]), int(c.get("n_split", 1)))
            for c in data["configs"]]


def _compile_and_get_ir(M, C, R, n_split):
    launcher  = compile_f16_down_proj(C=C, R=R, n_split=n_split)
    x_down    = torch.zeros(M, R, dtype=torch.float16)
    x         = torch.zeros(M, C, dtype=torch.float16)
    dn_weight = torch.zeros(R // 16, C // 16, 2, 16, 8, dtype=torch.float16)
    prev = os.environ.get("COMPILE_ONLY")
    os.environ["COMPILE_ONLY"] = "1"
    try:
        launcher(x_down, x, dn_weight, 0, M)
    finally:
        if prev is None: os.environ.pop("COMPILE_ONLY", None)
        else:            os.environ["COMPILE_ONLY"] = prev
    arts = list(launcher._mem_cache.values())
    if not arts:
        raise RuntimeError("_mem_cache empty after f16 down-proj compilation")
    return arts[0]._ir_text


def _decode_mlir_bin(ir_text, start):
    marker = 'bin = "'
    pos = ir_text.find(marker, start)
    if pos == -1:
        raise ValueError("'bin = \"' not found")
    i = pos + len(marker); out = bytearray()
    while i < len(ir_text):
        ch = ir_text[i]
        if ch == '\\':
            nxt = ir_text[i + 1]
            if nxt == '\\': out.append(0x5C); i += 2
            elif nxt == '"': out.append(0x22); i += 2
            else: out.append(int(ir_text[i + 1:i + 3], 16)); i += 3
        elif ch == '"': break
        else: out.append(ord(ch)); i += 1
    return bytes(out)


def _extract_hsaco(ir_text):
    a = ir_text.find("no_wave64")
    if a == -1:
        print("Warning: no_wave64 not found, using first object"); a = 0
    return _decode_mlir_bin(ir_text, a)


def _find_kernel_name(ir_text):
    m = re.search(r'#gpu\.kernel_metadata<"([^"]+)"', ir_text)
    return m.group(1) if m else "kernel_0"


_HEADER = """\
/* Auto-generated by export_f16_down_proj.py — do not edit.
 *
 * HSACO ELF for {kernel_name} (gfx1201, wave32/RDNA4).
 *
 * f16 down-projection (NO quantize):
 *   x_down[M,{R}] f16 = x[M,{C}]_f16 @ dn[{C},{R}]_f16
 * Used for the LAYER-0 precompute where the input x is f16 — reads x directly,
 * eliminating the fp8 quantize pass entirely. Bandwidth-bound; x_down is exact f16.
 *
 * Fixed dims: C={C}, R={R}
 *   x_down:    f16  [M, {R}]   (output, row-major)
 *   x:         f16  [M, {C}]
 *   dn_weight: f16  [{R_div16}, {C_div16}, 2, 16, 8]  preshuffled, [R,C] layout
 *
 * Grid:  ceil(M/{tile_m}) * {n_split} x 1 x 1   (runtime M; tail rows masked)
 * Block: {threads_per_block} x 1 x 1
 */
#pragma once
#include <hip/hip_runtime.h>
#include <stdint.h>
#include <stdio.h>

#define F16_DOWN_PROJ_C                 {C}
#define F16_DOWN_PROJ_R                 {R}
#define F16_DOWN_PROJ_TILE_M            {tile_m}
#define F16_DOWN_PROJ_N_SPLIT           {n_split}
#define F16_DOWN_PROJ_THREADS_PER_BLOCK {threads_per_block}

typedef struct {{ hipModule_t module; hipFunction_t func; }} f16_down_proj_Module_t;

static inline int f16_down_proj_Module_Load(f16_down_proj_Module_t *m, const char *hsaco_path) {{
    hipError_t err = hipModuleLoad(&m->module, hsaco_path);
    if (err != hipSuccess) {{ fprintf(stderr, "f16_down_proj: hipModuleLoad(%s): %s\\n", hsaco_path, hipGetErrorString(err)); return (int)err; }}
    err = hipModuleGetFunction(&m->func, m->module, "{kernel_name}");
    if (err != hipSuccess) {{ fprintf(stderr, "f16_down_proj: hipModuleGetFunction: %s\\n", hipGetErrorString(err)); (void)hipModuleUnload(m->module); return (int)err; }}
    return 0;
}}

static inline void f16_down_proj_Module_Unload(f16_down_proj_Module_t *m) {{
    if (m->module) (void)hipModuleUnload(m->module);
    m->module = NULL; m->func = NULL;
}}

/* Launch the f16 down-projection. M is runtime; tail rows (M %% tile_m) are masked. */
static inline int f16_down_proj_wrapper(
        const f16_down_proj_Module_t *m,
        hipDeviceptr_t d_x_down,     /* f16 [M,{R}] (output) */
        hipDeviceptr_t d_x,          /* f16 [M,{C}] */
        hipDeviceptr_t d_dn_weight,  /* f16 [{R_div16},{C_div16},2,16,8] */
        int32_t M,
        hipStream_t stream) {{
    int32_t grid_m            = (M + F16_DOWN_PROJ_TILE_M - 1) / F16_DOWN_PROJ_TILE_M;
    unsigned int total_blocks = (unsigned int)grid_m * F16_DOWN_PROJ_N_SPLIT;
    void *args[] = {{ &d_x_down, &d_x, &d_dn_weight, &M }};
    hipError_t err = hipModuleLaunchKernel(m->func, total_blocks, 1, 1,
            F16_DOWN_PROJ_THREADS_PER_BLOCK, 1, 1, 0, stream, args, NULL);
    if (err != hipSuccess) {{ fprintf(stderr, "f16_down_proj: launch: %s\\n", hipGetErrorString(err)); return (int)err; }}
    return 0;
}}
"""


def _export_one(M, C, R, n_split, artifacts_dir):
    name = f"rdna_f16_down_proj_C{C}_R{R}"
    print(f"\n[f16 down-proj M={M}, C={C}, R={R}, n_split={n_split}]  tile_m={TILE_M}, blocks=ceil(M/{TILE_M})*{n_split}")
    ir_text = _compile_and_get_ir(M, C, R, n_split)
    kernel_name = _find_kernel_name(ir_text)
    print(f"  Kernel: {kernel_name}  IR: {len(ir_text):,} chars")
    hsaco = _extract_hsaco(ir_text)
    if hsaco[:4] != b"\x7fELF":
        raise RuntimeError(f"Expected ELF magic, got {hsaco[:8].hex()}")
    os.makedirs(artifacts_dir, exist_ok=True)
    with open(os.path.join(artifacts_dir, f"{name}.hsaco"), "wb") as f:
        f.write(hsaco)
    with open(os.path.join(artifacts_dir, f"{name}.h"), "w") as f:
        f.write(_HEADER.format(kernel_name=kernel_name, C=C, R=R,
                               C_div16=C // 16, R_div16=R // 16,
                               tile_m=TILE_M, n_split=n_split, threads_per_block=THREADS_PER_BLOCK))
    print(f"  Wrote {len(hsaco):,} bytes → {artifacts_dir}/{name}.hsaco + .h")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--config", metavar="FILE")
    p.add_argument("--M", type=int, default=256)
    p.add_argument("--C", type=int, default=1024)
    p.add_argument("--R", type=int, default=128)
    p.add_argument("--n_split", type=int, default=1)
    args = p.parse_args()
    artifacts_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "artifacts")
    if args.config:
        for M, C, R, n_split in _load_configs(args.config, default_m=args.M):
            _export_one(M, C, R, n_split, artifacts_dir)
    else:
        _export_one(args.M, args.C, args.R, args.n_split, artifacts_dir)
