"""Export rdna_fp8_gemm_rotary as HSACO + C header.

Fused fp8 GEMM with in-epilogue rotary embedding (Q and K heads only).

Run with:
    python fly/export_fp8_gemm_rotary.py                       # defaults
    python fly/export_fp8_gemm_rotary.py --N 1536 --K 512      # explicit dims

Output (in fly/artifacts/):
    rdna_fp8_gemm_rotary_N{N}_K{K}_TM{tile_m}_TN{tile_n}.hsaco + .h
"""
import argparse
import os
import re
import sys

os.environ.setdefault("FLYDSL_RUNTIME_ENABLE_CACHE", "0")

import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rdna_fp8_gemm_rotary import compile_fp8_gemm_rotary


# ── Tile config (mirrors compile_fp8_gemm_rotary) ────────────────────────────

def _compute_config(M: int, N: int, K: int, tile_m: int = None) -> dict:
    if tile_m is None:
        tile_m = 64 if M >= 256 else 32
    tile_n = 256 if M >= 256 else 128
    if tile_m >= 128 and tile_n >= 128:
        waves_m, waves_n = 2, 2
    elif tile_m >= 64 and tile_n >= 128:
        waves_m, waves_n = 2, 2
    elif tile_n >= 256:
        waves_m, waves_n = 1, 2
    elif tile_m >= 64:
        waves_m, waves_n = 2, 1
    elif tile_n >= 128:
        waves_m, waves_n = 1, 2
    else:
        waves_m, waves_n = 1, 1
    return dict(
        tile_m=tile_m, tile_n=tile_n,
        waves_m=waves_m, waves_n=waves_n,
        threads_per_block=waves_m * waves_n * 32,
        total_blocks=(M // tile_m) * (N // tile_n),
    )


# ── Compilation ───────────────────────────────────────────────────────────────

def _compile_and_get_ir(M, N, K, nhead, head_dim, rotary_dim):
    rotary_half   = rotary_dim // 2
    dummy_seqlen  = 1024  # power-of-2; only used to size dummy buffers for compilation
    launcher = compile_fp8_gemm_rotary(
        M=M, N=N, K=K,
        nhead=nhead, head_dim=head_dim,
        rotary_dim=rotary_dim,
    )
    C       = torch.zeros(M, N, dtype=torch.float16)
    A       = torch.zeros(M, K, dtype=torch.uint8)
    B_shuf  = torch.zeros(N // 16, K // 16, 2, 16, 8, dtype=torch.uint8)
    scale_a = torch.zeros(M, dtype=torch.float32)
    scale_b = torch.zeros(N, dtype=torch.float32)
    sin_buf = torch.zeros(dummy_seqlen, rotary_half, dtype=torch.float32)
    cos_buf = torch.zeros(dummy_seqlen, rotary_half, dtype=torch.float32)
    prev = os.environ.get("COMPILE_ONLY")
    os.environ["COMPILE_ONLY"] = "1"
    try:
        launcher(C, A, B_shuf, scale_a, scale_b, sin_buf, cos_buf, 0, M, dummy_seqlen)
    finally:
        if prev is None:
            os.environ.pop("COMPILE_ONLY", None)
        else:
            os.environ["COMPILE_ONLY"] = prev
    artifacts = list(launcher._mem_cache.values())
    if not artifacts:
        raise RuntimeError("_mem_cache is empty after compilation")
    return artifacts[0]._ir_text


# ── MLIR binary extraction ────────────────────────────────────────────────────

def _decode_mlir_bin(ir_text: str, start: int) -> bytes:
    marker = 'bin = "'
    pos = ir_text.find(marker, start)
    if pos == -1:
        raise ValueError("'bin = \"' not found in IR text after position %d" % start)
    i = pos + len(marker)
    result = bytearray()
    while i < len(ir_text):
        c = ir_text[i]
        if c == '\\':
            nxt = ir_text[i + 1]
            if nxt == '\\':
                result.append(ord('\\'))
                i += 2
            elif nxt == '"':
                result.append(ord('"'))
                i += 2
            else:
                result.append(int(ir_text[i + 1: i + 3], 16))
                i += 3
        elif c == '"':
            break
        else:
            result.append(ord(c))
            i += 1
    return bytes(result)


def _extract_hsaco(ir_text: str, prefer_no_wave64: bool = True) -> bytes:
    if prefer_no_wave64:
        anchor = ir_text.find("no_wave64")
        if anchor == -1:
            print("Warning: no_wave64 variant not found, falling back to first object")
            anchor = 0
    else:
        anchor = 0
    return _decode_mlir_bin(ir_text, anchor)


def _find_kernel_name(ir_text: str) -> str:
    m = re.search(r'#gpu\.kernel_metadata<"([^"]+)"', ir_text)
    return m.group(1) if m else "kernel_gemm_rotary_0"


# ── C header template ─────────────────────────────────────────────────────────

_HEADER = """\
/* Auto-generated by export_fp8_gemm_rotary.py — do not edit.
 *
 * HSACO ELF for {kernel_name} (gfx1201, wave32/RDNA4).
 *
 * Fused fp8 GEMM + rotary embedding.
 * Computes: C[M,N] = rotary_embed(A[M,K] @ B[K,N])
 * where A, B are fp8_e4m3fn; output C is fp16.
 *
 * Layout: N={N} = 3 * {nhead} heads * {head_dim} head_dim
 *   Rotary applied to Q cols [0, {qk_chunk}) and K cols [{qk_chunk}, {qk2_chunk}).
 *   Each head: first rotary_dim={rotary_dim} elements rotated, rest written as-is.
 *   V cols [{qk2_chunk}, {N}) written unchanged.
 *
 * Fixed dims: N={N}, K={K}, rotary_half={rotary_half}
 *   A:       fp8_e4m3fn  [M, {K}]
 *   B:       fp8_e4m3fn  [{N_div16}, {K_div16}, 2, 16, 8]  — preshuffled
 *   C:       fp16        [M, {N}]
 *   scale_a: f32         [M]
 *   scale_b: f32         [{N}]
 *   sin:     f32         [seqlen, {rotary_half}]  — sin(theta) per (seq, rot)
 *   cos:     f32         [seqlen, {rotary_half}]  — cos(theta) per (seq, rot)
 *
 * seqlen is dynamic (passed as a runtime int32).
 * seq = flat_row % seqlen.  M must be a runtime multiple of tile_m.
 *
 * Grid:  (M / {tile_m}) * {grid_n} x 1 x 1
 * Block: {threads_per_block} x 1 x 1
 */
#pragma once
#include <hip/hip_runtime.h>
#include <stdint.h>
#include <stdio.h>

#define FP8_GEMM_ROTARY_N                  {N}
#define FP8_GEMM_ROTARY_K                  {K}
#define FP8_GEMM_ROTARY_TILE_M             {tile_m}
#define FP8_GEMM_ROTARY_TILE_N             {tile_n}
#define FP8_GEMM_ROTARY_THREADS_PER_BLOCK  {threads_per_block}
#define FP8_GEMM_ROTARY_HALF               {rotary_half}

typedef struct {{
    hipModule_t   module;
    hipFunction_t func;
}} fp8_gemm_rotary_Module_t;

static inline int fp8_gemm_rotary_Module_Load(fp8_gemm_rotary_Module_t *m, const char *hsaco_path) {{
    hipError_t err = hipModuleLoad(&m->module, hsaco_path);
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_gemm_rotary: hipModuleLoad(%s): %s\\n", hsaco_path, hipGetErrorString(err));
        return (int)err;
    }}
    err = hipModuleGetFunction(&m->func, m->module, "{kernel_name}");
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_gemm_rotary: hipModuleGetFunction: %s\\n", hipGetErrorString(err));
        (void)hipModuleUnload(m->module);
        return (int)err;
    }}
    return 0;
}}

static inline void fp8_gemm_rotary_Module_Unload(fp8_gemm_rotary_Module_t *m) {{
    if (m->module) (void)hipModuleUnload(m->module);
    m->module = NULL;
    m->func   = NULL;
}}

/* Launch the fused GEMM+rotary kernel.
 * M must be a runtime multiple of FP8_GEMM_ROTARY_TILE_M; N and K are fixed at export.
 * d_B_shuf must be in preshuffled layout [{N_div16},{K_div16},2,16,8].
 * d_sin, d_cos: f32 [seqlen, {rotary_half}] — row = seq pos, col = rot index.
 * seqlen is the runtime sequence length (any positive value; sin/cos buffer must have seqlen rows).
 * Rotary applied to Q and K; V cols written unchanged. */
static inline int fp8_gemm_rotary_wrapper(
        const fp8_gemm_rotary_Module_t *m,
        hipDeviceptr_t d_C,       /* fp16  [M, {N}] */
        hipDeviceptr_t d_A,       /* fp8   [M, {K}] */
        hipDeviceptr_t d_B_shuf,  /* fp8   [{N_div16},{K_div16},2,16,8] */
        hipDeviceptr_t d_scale_a, /* f32   [M] */
        hipDeviceptr_t d_scale_b, /* f32   [{N}] */
        hipDeviceptr_t d_sin,     /* f32   [seqlen,{rotary_half}] */
        hipDeviceptr_t d_cos,     /* f32   [seqlen,{rotary_half}] */
        int32_t M,
        int32_t seqlen,
        hipStream_t stream) {{
    if (M % FP8_GEMM_ROTARY_TILE_M != 0) {{
        fprintf(stderr, "fp8_gemm_rotary: M=%d not divisible by tile_m=%d\\n", M, FP8_GEMM_ROTARY_TILE_M);
        return -1;
    }}
    int32_t grid_m = M / FP8_GEMM_ROTARY_TILE_M;
    unsigned int total_blocks = (unsigned int)grid_m * ({N} / FP8_GEMM_ROTARY_TILE_N);
    void *args[] = {{ &d_C, &d_A, &d_B_shuf, &d_scale_a, &d_scale_b, &d_sin, &d_cos, &grid_m, &seqlen }};
    hipError_t err = hipModuleLaunchKernel(
            m->func,
            total_blocks, 1, 1,
            FP8_GEMM_ROTARY_THREADS_PER_BLOCK, 1, 1,
            0, stream, args, NULL);
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_gemm_rotary: hipModuleLaunchKernel: %s\\n", hipGetErrorString(err));
        return (int)err;
    }}
    return 0;
}}
"""


def _write_text(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)


def _export_one(M, N, K, nhead, head_dim, rotary_dim, artifacts_dir):
    rotary_half = rotary_dim // 2
    cfg  = _compute_config(M, N, K)
    name = f"rdna_fp8_gemm_rotary_N{N}_K{K}_TM{cfg['tile_m']}_TN{cfg['tile_n']}"
    print(f"\n[M={M}, N={N}, K={K}]  nhead={nhead}, head_dim={head_dim}, "
          f"rotary_dim={rotary_dim}  (seqlen dynamic)")
    print(f"  tile_m={cfg['tile_m']}, tile_n={cfg['tile_n']}, "
          f"waves=({cfg['waves_m']},{cfg['waves_n']}), "
          f"threads={cfg['threads_per_block']}, blocks={cfg['total_blocks']}")

    ir_text     = _compile_and_get_ir(M, N, K, nhead, head_dim, rotary_dim)
    kernel_name = _find_kernel_name(ir_text)
    print(f"  Kernel: {kernel_name}  IR: {len(ir_text):,} chars")

    hsaco = _extract_hsaco(ir_text, prefer_no_wave64=True)
    if hsaco[:4] != b"\x7fELF":
        raise RuntimeError(f"Expected ELF magic, got: {hsaco[:8].hex()}")

    hsaco_path  = os.path.join(artifacts_dir, f"{name}.hsaco")
    header_path = os.path.join(artifacts_dir, f"{name}.h")
    os.makedirs(artifacts_dir, exist_ok=True)
    with open(hsaco_path, "wb") as f:
        f.write(hsaco)

    header = _HEADER.format(
        kernel_name=kernel_name,
        N=N, K=K,
        N_div16=N // 16, K_div16=K // 16,
        nhead=nhead, head_dim=head_dim,
        rotary_dim=rotary_dim, rotary_half=rotary_half,
        qk_chunk=nhead * head_dim,
        qk2_chunk=2 * nhead * head_dim,
        tile_m=cfg["tile_m"], tile_n=cfg["tile_n"],
        threads_per_block=cfg["threads_per_block"],
        total_blocks=cfg["total_blocks"],
        grid_n=N // cfg["tile_n"],
    )
    _write_text(header_path, header)
    print(f"  Wrote {len(hsaco):,} bytes → {hsaco_path}")
    print(f"  Wrote header → {header_path}")


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Export fused fp8 GEMM + rotary embedding kernel as HSACO + C header."
    )
    parser.add_argument("--M",          type=int, default=256,   help="Batch dim for tile selection (default: 256)")
    parser.add_argument("--N",          type=int, default=1536,  help="QKV output dim = 3*nhead*head_dim (default: 1536)")
    parser.add_argument("--K",          type=int, default=512,   help="Input dim (default: 512)")
    parser.add_argument("--nhead",      type=int, default=8,     help="Number of attention heads (default: 8)")
    parser.add_argument("--head-dim",   type=int, default=64,    help="Head dimension (default: 64)")
    parser.add_argument("--rotary-dim", type=int, default=64,    help="Rotary dimension per head (default: 64 = full head_dim, matches OpenFish)")
    args = parser.parse_args()

    artifacts_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "artifacts")
    _export_one(
        args.M, args.N, args.K,
        args.nhead, args.head_dim, args.rotary_dim,
        artifacts_dir,
    )
