"""Export rdna_fp8_down_proj (compile_fp8_down_proj) as HSACO + C header.

Down-projection precompute for the fused LSTM:
  x_down[M,R] f16 = (x[M,C]_fp8 @ dn[C,R]_fp8) * scale_x[M] (per-token) * scale_dn (scalar)
Run once over M = T*N (batched, outside the timestep loop). Output is the tiny x_down
that the fused LSTM reads instead of the 2-4 GB ih[T,N,4H] tensor.

Run:
    python fly/export_fp8_down_proj.py
    python fly/export_fp8_down_proj.py --config fly/export_configs/rdna_fp8_down_proj.toml

Output: artifacts/rdna_fp8_down_proj_C{C}_R{R}.hsaco + .h
"""
import argparse
import os
import re
import sys

try:
    import tomllib
except ModuleNotFoundError:
    try:
        import tomli as tomllib  # type: ignore[no-redef]
    except ModuleNotFoundError:
        tomllib = None  # type: ignore[assignment]

os.environ.setdefault("FLYDSL_RUNTIME_ENABLE_CACHE", "0")

import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rdna_fp8_factored_gemm import compile_fp8_down_proj

TILE_M = 32
THREADS_PER_BLOCK = 64   # waves 1x2


def _load_configs(path, default_m=256):
    if tomllib is None:
        raise RuntimeError("tomllib not available — Python 3.11+ or `pip install tomli`")
    with open(path, "rb") as f:
        data = tomllib.load(f)
    return [(int(c.get("M", default_m)), int(c["C"]), int(c["R"]),
             int(c.get("n_split", 1)), str(c.get("tag", "")))
            for c in data["configs"]]


def _compile_and_get_ir(M, C, R, n_split):
    launcher  = compile_fp8_down_proj(C=C, R=R, n_split=n_split)
    x_down    = torch.zeros(M, R, dtype=torch.float16)
    x         = torch.zeros(M, C, dtype=torch.uint8)
    scale_x   = torch.zeros(M, dtype=torch.float32)
    dn_weight = torch.zeros(R // 16, C // 16, 2, 16, 8, dtype=torch.uint8)
    scale_dn  = torch.zeros(1, dtype=torch.float32)
    prev = os.environ.get("COMPILE_ONLY")
    os.environ["COMPILE_ONLY"] = "1"
    try:
        launcher(x_down, x, scale_x, dn_weight, scale_dn, 0, M)
    finally:
        if prev is None: os.environ.pop("COMPILE_ONLY", None)
        else:            os.environ["COMPILE_ONLY"] = prev
    arts = list(launcher._mem_cache.values())
    if not arts:
        raise RuntimeError("_mem_cache empty after down-proj compilation")
    return arts[0]._ir_text


def _decode_mlir_bin(ir_text, start):
    marker = 'bin = "'
    pos = ir_text.find(marker, start)
    if pos == -1:
        raise ValueError("'bin = \"' not found")
    i = pos + len(marker); out = bytearray()
    while i < len(ir_text):
        ch = ir_text[i]
        if ch == '\\':
            nxt = ir_text[i + 1]
            if nxt == '\\': out.append(0x5C); i += 2
            elif nxt == '"': out.append(0x22); i += 2
            else: out.append(int(ir_text[i + 1:i + 3], 16)); i += 3
        elif ch == '"': break
        else: out.append(ord(ch)); i += 1
    return bytes(out)


def _extract_hsaco(ir_text):
    a = ir_text.find("no_wave64")
    if a == -1:
        print("Warning: no_wave64 not found, using first object"); a = 0
    return _decode_mlir_bin(ir_text, a)


def _find_kernel_name(ir_text):
    m = re.search(r'#gpu\.kernel_metadata<"([^"]+)"', ir_text)
    return m.group(1) if m else "kernel_0"


_HEADER = """\
/* Auto-generated by export_fp8_down_proj.py — do not edit.
 *
 * HSACO ELF for {kernel_name} (gfx1201, wave32/RDNA4).
 *
 * Down-projection precompute for the fused LSTM:
 *   x_down[M,{R}] f16 = (x[M,{C}]_fp8 @ dn[{C},{R}]_fp8) * scale_x[M] * scale_dn
 *   (per-token scale_x, scalar scale_dn). Run once over M = T*N (batched).
 *
 * Fixed dims: C={C}, R={R}
 *   x_down:    f16        [M, {R}]   (output, row-major)
 *   x:         fp8 bytes  [M, {C}]   (per-token quantized)
 *   scale_x:   f32        [M]        (per-token)
 *   dn_weight: fp8        [{R_div16}, {C_div16}, 2, 16, 8]  preshuffled, [R,C] layout
 *   scale_dn:  f32        [1]        (scalar, broadcast)
 *
 * Grid:  ceil(M/{tile_m}) * {n_split} x 1 x 1   (runtime M; tail rows masked; R split n_split ways)
 * Block: {threads_per_block} x 1 x 1
 */
#pragma once
#include <hip/hip_runtime.h>
#include <stdint.h>
#include <stdio.h>

#define FP8_DOWN_PROJ_C                 {C}
#define FP8_DOWN_PROJ_R                 {R}
#define FP8_DOWN_PROJ_TILE_M            {tile_m}
#define FP8_DOWN_PROJ_N_SPLIT           {n_split}
#define FP8_DOWN_PROJ_THREADS_PER_BLOCK {threads_per_block}

typedef struct {{ hipModule_t module; hipFunction_t func; }} fp8_down_proj_Module_t;

static inline int fp8_down_proj_Module_Load(fp8_down_proj_Module_t *m, const char *hsaco_path) {{
    hipError_t err = hipModuleLoad(&m->module, hsaco_path);
    if (err != hipSuccess) {{ fprintf(stderr, "fp8_down_proj: hipModuleLoad(%s): %s\\n", hsaco_path, hipGetErrorString(err)); return (int)err; }}
    err = hipModuleGetFunction(&m->func, m->module, "{kernel_name}");
    if (err != hipSuccess) {{ fprintf(stderr, "fp8_down_proj: hipModuleGetFunction: %s\\n", hipGetErrorString(err)); (void)hipModuleUnload(m->module); return (int)err; }}
    return 0;
}}

static inline void fp8_down_proj_Module_Unload(fp8_down_proj_Module_t *m) {{
    if (m->module) (void)hipModuleUnload(m->module);
    m->module = NULL; m->func = NULL;
}}

/* Launch the down-projection. M is a runtime value; tail rows (M %% tile_m) are masked. */
static inline int fp8_down_proj_wrapper(
        const fp8_down_proj_Module_t *m,
        hipDeviceptr_t d_x_down,     /* f16 [M,{R}] (output) */
        hipDeviceptr_t d_x,          /* fp8 [M,{C}] */
        hipDeviceptr_t d_scale_x,    /* f32 [M] */
        hipDeviceptr_t d_dn_weight,  /* fp8 [{R_div16},{C_div16},2,16,8] */
        hipDeviceptr_t d_scale_dn,   /* f32 [1] */
        int32_t M,
        hipStream_t stream) {{
    int32_t grid_m            = (M + FP8_DOWN_PROJ_TILE_M - 1) / FP8_DOWN_PROJ_TILE_M;
    unsigned int total_blocks = (unsigned int)grid_m * FP8_DOWN_PROJ_N_SPLIT;
    void *args[] = {{ &d_x_down, &d_x, &d_scale_x, &d_dn_weight, &d_scale_dn, &M }};
    hipError_t err = hipModuleLaunchKernel(m->func, total_blocks, 1, 1,
            FP8_DOWN_PROJ_THREADS_PER_BLOCK, 1, 1, 0, stream, args, NULL);
    if (err != hipSuccess) {{ fprintf(stderr, "fp8_down_proj: launch: %s\\n", hipGetErrorString(err)); return (int)err; }}
    return 0;
}}
"""


def _write_text(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)


def _export_one(M, C, R, n_split, artifacts_dir, tag=""):
    # tag != "" gives the artifact distinct C symbols + filename so multiple n_split
    # variants can coexist (e.g. precompute n_split=1 + per-step hh_down n_split=4).
    name = f"rdna_fp8_down_proj_C{C}_R{R}" if not tag else f"rdna_fp8_down_proj_{tag}_C{C}_R{R}"
    print(f"\n[down-proj M={M}, C={C}, R={R}, n_split={n_split}, tag='{tag}']  tile_m={TILE_M}, "
          f"threads={THREADS_PER_BLOCK}, blocks=ceil(M/{TILE_M})*{n_split}")
    ir_text = _compile_and_get_ir(M, C, R, n_split)
    kernel_name = _find_kernel_name(ir_text)
    print(f"  Kernel: {kernel_name}  IR: {len(ir_text):,} chars")
    hsaco = _extract_hsaco(ir_text)
    if hsaco[:4] != b"\x7fELF":
        raise RuntimeError(f"Expected ELF magic, got {hsaco[:8].hex()}")
    hsaco_path  = os.path.join(artifacts_dir, f"{name}.hsaco")
    header_path = os.path.join(artifacts_dir, f"{name}.h")
    header = _HEADER.format(
        kernel_name=kernel_name, C=C, R=R,
        C_div16=C // 16, R_div16=R // 16,
        tile_m=TILE_M, n_split=n_split, threads_per_block=THREADS_PER_BLOCK)
    if tag:
        # Distinct C identifiers so this header can be included alongside the default one.
        header = header.replace("FP8_DOWN_PROJ", f"FP8_DOWN_PROJ_{tag.upper()}")
        header = header.replace("fp8_down_proj", f"fp8_down_proj_{tag}")
    os.makedirs(artifacts_dir, exist_ok=True)
    with open(hsaco_path, "wb") as f:
        f.write(hsaco)
    _write_text(header_path, header)
    print(f"  Wrote {len(hsaco):,} bytes → {hsaco_path}")
    print(f"  Wrote header → {header_path}")


if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Export down-projection kernel as HSACO + C header.")
    p.add_argument("--config", metavar="FILE")
    p.add_argument("--M", type=int, default=256)
    p.add_argument("--C", type=int, default=1024)
    p.add_argument("--R", type=int, default=128)
    p.add_argument("--n_split", type=int, default=4)
    p.add_argument("--tag", type=str, default="")
    args = p.parse_args()
    artifacts_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "artifacts")
    if args.config:
        cfgs = _load_configs(args.config, default_m=args.M)
        print(f"Batch export: {len(cfgs)} config(s) from {args.config}")
        for M, C, R, n_split, tag in cfgs:
            _export_one(M, C, R, n_split, artifacts_dir, tag)
        print(f"\nDone. {len(cfgs)} config(s) → {artifacts_dir}/")
    else:
        _export_one(args.M, args.C, args.R, args.n_split, artifacts_dir, args.tag)
