"""Export rdna_fp8_preshuffle_gemm as a raw HSACO binary + C header.

Configuration: M=32 (fixed; runtime-dynamic), N and K from args or config file.

Run with:
    python export_fp8_gemm.py                                    # N=8192, K=6144 (defaults)
    python export_fp8_gemm.py --N 4096 --K 3072                  # single config
    python export_fp8_gemm.py --config export_configs/rdna_fp8_gemm.toml  # batch

Outputs (single):  artifacts/rdna_fp8_gemm.hsaco + .h
Outputs (batch):   artifacts/rdna_fp8_gemm_N{N}_K{K}.hsaco + .h  (one pair per config)

For an all-in-one embedded header use:
    python export_fp8_gemm_embedded.py
"""
import argparse
import os
import re
import sys

try:
    import tomllib
except ModuleNotFoundError:
    try:
        import tomli as tomllib  # type: ignore[no-redef]
    except ModuleNotFoundError:
        tomllib = None  # type: ignore[assignment]

os.environ.setdefault("FLYDSL_RUNTIME_ENABLE_CACHE", "0")

import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rdna_fp8_preshuffle_gemm import compile_fp8_gemm


# ── Tile / wave auto-selection (mirrors compile_fp8_gemm) ─────────────────────

def _compute_config(M: int, N: int, K: int, tile_m: int = None) -> dict:
    """Return tile/wave constants for the given shape, matching compile_fp8_gemm."""
    if tile_m is None:
        tile_m = 64 if M >= 256 else 32
    tile_n = 256 if M >= 256 else 128

    if tile_m >= 128 and tile_n >= 128:
        waves_m, waves_n = 2, 2
    elif tile_m >= 64 and tile_n >= 128:
        waves_m, waves_n = 2, 2
    elif tile_n >= 256:
        waves_m, waves_n = 1, 2
    elif tile_m >= 64:
        waves_m, waves_n = 2, 1
    elif tile_n >= 128:
        waves_m, waves_n = 1, 2
    else:
        waves_m, waves_n = 1, 1

    return dict(
        tile_m=tile_m,
        tile_n=tile_n,
        waves_m=waves_m,
        waves_n=waves_n,
        threads_per_block=waves_m * waves_n * 32,
        total_blocks=(M // tile_m) * (N // tile_n),
    )


def _load_configs(path: str, default_m: int = 32) -> list[tuple[int, int, int]]:
    """Parse a TOML config file and return a list of (M, N, K) triples.

    Each [[configs]] entry must have N and K; M is optional and falls back to default_m.
    """
    if tomllib is None:
        raise RuntimeError(
            "tomllib not available — upgrade to Python 3.11+ or `pip install tomli`"
        )
    with open(path, "rb") as f:
        data = tomllib.load(f)
    return [(int(c.get("M", default_m)), int(c["N"]), int(c["K"])) for c in data["configs"]]


# ── Compilation ───────────────────────────────────────────────────────────────

def _compile_and_get_ir(M: int, N: int, K: int):
    launcher = compile_fp8_gemm(M=M, N=N, K=K)
    C       = torch.zeros(M, N, dtype=torch.float16)
    A       = torch.zeros(M, K, dtype=torch.uint8)
    B_shuf  = torch.zeros(N // 16, K // 16, 2, 16, 8, dtype=torch.uint8)
    scale_a = torch.zeros(M, dtype=torch.float32)
    scale_b = torch.zeros(N, dtype=torch.float32)
    prev = os.environ.get("COMPILE_ONLY")
    os.environ["COMPILE_ONLY"] = "1"
    try:
        launcher(C, A, B_shuf, scale_a, scale_b, 0, M)
    finally:
        if prev is None:
            os.environ.pop("COMPILE_ONLY", None)
        else:
            os.environ["COMPILE_ONLY"] = prev
    artifacts = list(launcher._mem_cache.values())
    if not artifacts:
        raise RuntimeError("_mem_cache is empty after compilation")
    return artifacts[0]._ir_text


# ── MLIR string decoding (same as export_vec_add.py) ─────────────────────────

def _decode_mlir_bin(ir_text: str, start: int) -> bytes:
    marker = 'bin = "'
    pos = ir_text.find(marker, start)
    if pos == -1:
        raise ValueError("'bin = \"' not found in IR text after position %d" % start)
    i = pos + len(marker)
    result = bytearray()
    while i < len(ir_text):
        c = ir_text[i]
        if c == '\\':
            nxt = ir_text[i + 1]
            if nxt == '\\':
                result.append(ord('\\'))
                i += 2
            elif nxt == '"':
                result.append(ord('"'))
                i += 2
            else:
                result.append(int(ir_text[i + 1: i + 3], 16))
                i += 3
        elif c == '"':
            break
        else:
            result.append(ord(c))
            i += 1
    return bytes(result)


def _extract_hsaco(ir_text: str, prefer_no_wave64: bool = True) -> bytes:
    if prefer_no_wave64:
        anchor = ir_text.find("no_wave64")
        if anchor == -1:
            print("Warning: no_wave64 variant not found, falling back to first object")
            anchor = 0
    else:
        anchor = 0
    return _decode_mlir_bin(ir_text, anchor)


def _find_kernel_name(ir_text: str) -> str:
    m = re.search(r'#gpu\.kernel_metadata<"([^"]+)"', ir_text)
    return m.group(1) if m else "kernel_gemm_0"


# ── C header template ────────────────────────────────────────────────────────

_HEADER = """\
/* Auto-generated by export_fp8_gemm.py — do not edit.
 *
 * HSACO ELF for {kernel_name} (gfx1201, wave32/RDNA4).
 *
 * Computes:  C[M,N] = (A[M,K] @ B[K,N]) * scale_a[M,1] * scale_b[1,N]
 * where A and B are fp8_e4m3fn, output C is fp16.
 *
 * Fixed dimensions: M={M}, N={N}, K={K}
 *   A:       fp8_e4m3fn  [{M}, {K}]         — raw row-major
 *   B:       fp8_e4m3fn  [{N}//16, {K}//16, 2, 16, 8]  — preshuffled (see below)
 *   C:       fp16        [{M}, {N}]         — output
 *   scale_a: f32         [{M}]              — per-token (per-row) activation scale
 *   scale_b: f32         [{N}]              — per-channel weight scale
 *
 * B must be preshuffled before calling the kernel.
 * C++ preshuffle: see preshuffle_b() in main_rdna_fp8_gemm.cpp
 * Python preshuffle: fly.rdna_fp8_preshuffle_gemm.preshuffle_b_fp8
 *
 * Grid:  {total_blocks} x 1 x 1
 * Block: {threads_per_block} x 1 x 1
 * Build: hipcc -o main_rdna_fp8_gemm main_rdna_fp8_gemm.cpp
 * The .hsaco file must be accessible at the path passed to fp8_gemm_Module_Load.
 */
#pragma once
#include <hip/hip_runtime.h>
#include <stdint.h>
#include <stdio.h>

/* ── Compiled-in constants (N, K, tile sizes fixed at export time) ── */
#define FP8_GEMM_N                  {N}
#define FP8_GEMM_K                  {K}
#define FP8_GEMM_TILE_M             {tile_m}
#define FP8_GEMM_TILE_N             {tile_n}
#define FP8_GEMM_THREADS_PER_BLOCK  {threads_per_block}

/* ── Module handle ── */
typedef struct {{
    hipModule_t   module;
    hipFunction_t func;
}} fp8_gemm_Module_t;

/* Load the kernel from a .hsaco file on disk. */
static inline int fp8_gemm_Module_Load(fp8_gemm_Module_t *m, const char *hsaco_path) {{
    hipError_t err = hipModuleLoad(&m->module, hsaco_path);
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_gemm: hipModuleLoad(%s): %s\\n", hsaco_path, hipGetErrorString(err));
        return (int)err;
    }}
    err = hipModuleGetFunction(&m->func, m->module, "{kernel_name}");
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_gemm: hipModuleGetFunction: %s\\n", hipGetErrorString(err));
        (void)hipModuleUnload(m->module);
        return (int)err;
    }}
    return 0;
}}

static inline void fp8_gemm_Module_Unload(fp8_gemm_Module_t *m) {{
    if (m->module) (void)hipModuleUnload(m->module);
    m->module = NULL;
    m->func   = NULL;
}}

/* Launch the kernel.
 * M must be a runtime multiple of FP8_GEMM_TILE_M; N and K are fixed at export time.
 * d_B_shuf must already be in preshuffled layout [{N_div16},{K_div16},2,16,8].
 * Returns 0 on success, non-zero HIP error code otherwise. */
static inline int fp8_gemm_wrapper(
        const fp8_gemm_Module_t *m,
        hipDeviceptr_t d_C,       /* bf16  [M, {N}] */
        hipDeviceptr_t d_A,       /* fp8   [M, {K}] */
        hipDeviceptr_t d_B_shuf,  /* fp8   [{N_div16},{K_div16},2,16,8] */
        hipDeviceptr_t d_scale_a, /* f32   [M] */
        hipDeviceptr_t d_scale_b, /* f32   [{N}] */
        int32_t M,
        hipStream_t stream) {{
    if (M % FP8_GEMM_TILE_M != 0) {{
        fprintf(stderr, "fp8_gemm: M=%d not divisible by tile_m=%d\\n", M, FP8_GEMM_TILE_M);
        return -1;
    }}
    int32_t grid_m = M / FP8_GEMM_TILE_M;
    unsigned int total_blocks = (unsigned int)grid_m * ({N} / FP8_GEMM_TILE_N);
    void *args[] = {{ &d_C, &d_A, &d_B_shuf, &d_scale_a, &d_scale_b, &grid_m }};
    hipError_t err = hipModuleLaunchKernel(
            m->func,
            total_blocks, 1, 1,
            FP8_GEMM_THREADS_PER_BLOCK, 1, 1,
            0, stream, args, NULL);
    if (err != hipSuccess) {{
        fprintf(stderr, "fp8_gemm: hipModuleLaunchKernel: %s\\n", hipGetErrorString(err));
        return (int)err;
    }}
    return 0;
}}
"""

def _fmt(template: str, kernel_name: str,
         M: int, N: int, K: int, cfg: dict) -> str:
    return template.format(
        kernel_name=kernel_name,
        M=M, N=N, K=K,
        N_div16=N // 16, K_div16=K // 16,
        tile_m=cfg["tile_m"], tile_n=cfg["tile_n"],
        total_blocks=cfg["total_blocks"],
        threads_per_block=cfg["threads_per_block"],
    )


def _write_text(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)


def _generate_hsaco(hsaco: bytes, kernel_name: str, artifacts_dir: str,
                    M: int, N: int, K: int, cfg: dict,
                    name: str = "rdna_fp8_gemm") -> None:
    hsaco_path  = os.path.join(artifacts_dir, f"{name}.hsaco")
    header_path = os.path.join(artifacts_dir, f"{name}.h")
    os.makedirs(artifacts_dir, exist_ok=True)
    with open(hsaco_path, "wb") as f:
        f.write(hsaco)
    _write_text(header_path, _fmt(_HEADER, kernel_name, M, N, K, cfg))
    print(f"  Wrote {len(hsaco):,} bytes of HSACO → {hsaco_path}")
    print(f"  Wrote header (hipModuleLoad) → {header_path}")


def _export_one(M: int, N: int, K: int, artifacts_dir: str) -> None:
    cfg = _compute_config(M, N, K)
    name = f"rdna_fp8_gemm_N{N}_K{K}_TM{cfg['tile_m']}_TN{cfg['tile_n']}"
    print(f"\n[M={M}, N={N}, K={K}]  tile_m={cfg['tile_m']}, tile_n={cfg['tile_n']}, "
          f"waves=({cfg['waves_m']},{cfg['waves_n']}), "
          f"threads={cfg['threads_per_block']}, blocks={cfg['total_blocks']}")

    ir_text = _compile_and_get_ir(M, N, K)
    kernel_name = _find_kernel_name(ir_text)
    print(f"  Kernel: {kernel_name}  IR: {len(ir_text):,} chars")

    hsaco = _extract_hsaco(ir_text, prefer_no_wave64=True)
    if hsaco[:4] != b"\x7fELF":
        raise RuntimeError(f"Expected ELF magic, got: {hsaco[:8].hex()}")

    _generate_hsaco(hsaco, kernel_name, artifacts_dir, M, N, K, cfg, name=name)


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export fp8 GEMM kernel as HSACO + C header.")
    parser.add_argument("--config", metavar="FILE",
                        help="TOML config file with a list of M,N,K configs to batch-export")
    parser.add_argument("--M", type=int, default=32,  help="Batch dimension for tile selection (default: 32)")
    parser.add_argument("--N", type=int, default=8192, help="Output dimension (default: 8192)")
    parser.add_argument("--K", type=int, default=6144, help="Reduction dimension (default: 6144)")
    args = parser.parse_args()

    artifacts_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "artifacts")

    if args.config:
        configs = _load_configs(args.config, default_m=args.M)
        print(f"Batch export: {len(configs)} config(s) from {args.config}")
        for M, N, K in configs:
            _export_one(M, N, K, artifacts_dir)
        print(f"\nDone. {len(configs)} kernel(s) exported to {artifacts_dir}/")
    else:
        _export_one(args.M, args.N, args.K, artifacts_dir)
