/* Minimal HIP driver for the exported vectorAdd kernel.
 *
 * Build:
 *   hipcc -o main_vec_add main_vec_add.cpp
 *
 * Run:
 *   ./main_vec_add            # default N=128
 *   ./main_vec_add 1000       # any N
 *   ./main_vec_add 100        # non-multiple of 64 (kernel bounds-checks)
 *
 * Requires artifacts/vec_add.h, generated by:
 *   python export_vec_add.py
 */
#include "artifacts/vec_add.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>

#define CHECK_HIP(expr)                                                         \
    do {                                                                        \
        hipError_t _e = (expr);                                                 \
        if (_e != hipSuccess) {                                                 \
            fprintf(stderr, "HIP error at %s:%d — %s\n",                       \
                    __FILE__, __LINE__, hipGetErrorString(_e));                  \
            return 1;                                                           \
        }                                                                       \
    } while (0)

int main(int argc, char *argv[]) {
    int N = (argc > 1) ? atoi(argv[1]) : 128;
    if (N <= 0) {
        fprintf(stderr, "N must be positive\n");
        return 1;
    }
    printf("N = %d\n", N);

    /* Host buffers */
    float *h_A = new float[N];
    float *h_B = new float[N];
    float *h_C = new float[N];
    for (int i = 0; i < N; i++) {
        h_A[i] = (float)i;
        h_B[i] = (float)(N - i);
    }

    /* Device buffers */
    float *d_A, *d_B, *d_C;
    CHECK_HIP(hipMalloc(&d_A, N * sizeof(float)));
    CHECK_HIP(hipMalloc(&d_B, N * sizeof(float)));
    CHECK_HIP(hipMalloc(&d_C, N * sizeof(float)));
    CHECK_HIP(hipMemcpy(d_A, h_A, N * sizeof(float), hipMemcpyHostToDevice));
    CHECK_HIP(hipMemcpy(d_B, h_B, N * sizeof(float), hipMemcpyHostToDevice));

    /* Load the HSACO module */
    vec_add_Module_t mod = {};
    if (vec_add_Module_Load(&mod) != 0)
        return 1;

    /* Launch */
    hipStream_t stream;
    CHECK_HIP(hipStreamCreate(&stream));
    if (vec_add_wrapper(&mod,
                        (hipDeviceptr_t)d_A,
                        (hipDeviceptr_t)d_B,
                        (hipDeviceptr_t)d_C,
                        (int32_t)N, stream) != 0)
        return 1;
    CHECK_HIP(hipStreamSynchronize(stream));

    /* Copy result back and verify */
    CHECK_HIP(hipMemcpy(h_C, d_C, N * sizeof(float), hipMemcpyDeviceToHost));

    bool correct = true;
    for (int i = 0; i < N; i++) {
        float expected = h_A[i] + h_B[i];
        if (fabsf(h_C[i] - expected) > 1e-5f) {
            fprintf(stderr, "Mismatch at i=%d: got %.6f, expected %.6f\n",
                    i, h_C[i], expected);
            correct = false;
            break;
        }
    }
    printf("Result correct: %s\n", correct ? "true" : "false");

    /* Cleanup */
    CHECK_HIP(hipStreamDestroy(stream));
    (void)hipFree(d_A);
    (void)hipFree(d_B);
    (void)hipFree(d_C);
    vec_add_Module_Unload(&mod);
    delete[] h_A;
    delete[] h_B;
    delete[] h_C;

    return correct ? 0 : 1;
}
