/* HIP driver for the exported rdna_fp8_preshuffle_gemm kernel.
 *
 * Build:
 *   hipcc -o build/main_rdna_fp8_gemm main_rdna_fp8_gemm.cpp
 *
 * Run:
 *   ./build/main_rdna_fp8_gemm          # default M=32
 *   ./build/main_rdna_fp8_gemm 64       # any M that is a multiple of FP8_GEMM_TILE_M
 *
 * N and K are fixed at export time (see FP8_GEMM_N / FP8_GEMM_K in the header).
 * Test: fills A and B with fp8(1.0), scales = 1.0.
 * Expected output: every C[m,n] = K (in bf16).
 *
 * For a full accuracy sweep over random inputs use:
 *   python verify_fp8_gemm.py
 *
 * Requires artifacts/rdna_fp8_gemm.h + artifacts/rdna_fp8_gemm.hsaco, generated by:
 *   python export_fp8_gemm.py
 */

#define KERNEL_HSACO  "artifacts/rdna_fp8_gemm_N512_K4096_TM32_TN256.hsaco"
#define KERNEL_HEADER "artifacts/rdna_fp8_gemm_N512_K4096_TM32_TN256.h"

#include KERNEL_HEADER

#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>

/* N and K are fixed by the compiled kernel; M is passed at runtime. */

/* ── HIP error helper ────────────────────────────────────────────────────── */
#define CHECK_HIP(expr)                                                         \
    do {                                                                        \
        hipError_t _e = (expr);                                                 \
        if (_e != hipSuccess) {                                                 \
            fprintf(stderr, "HIP error at %s:%d — %s\n",                       \
                    __FILE__, __LINE__, hipGetErrorString(_e));                  \
            return 1;                                                           \
        }                                                                       \
    } while (0)

/* ── fp8_e4m3fn decode ───────────────────────────────────────────────────── */
static float decode_fp8(uint8_t v) {
    int sign = (v >> 7) & 1;
    int exp  = (v >> 3) & 0xF;
    int mant =  v       & 0x7;
    if (exp == 0 && mant == 0) return 0.0f;
    if (exp == 15 && mant == 7) return (float)__builtin_nanf("");
    float f = (exp == 0)
        ? ldexpf((float)mant / 8.0f, -6)
        : ldexpf(1.0f + (float)mant / 8.0f, exp - 7);
    return sign ? -f : f;
}

/* fp8_e4m3fn encode — nearest representable, clamped to [-448, 448] */
static uint8_t encode_fp8(float val) {
    if (val == 0.0f) return 0x00;
    uint8_t sign = (val < 0.0f) ? 0x80 : 0x00;
    val = fabsf(val);
    val = fminf(val, 448.0f);
    /* find exponent */
    int e;
    float m = frexpf(val, &e);   /* val = m * 2^e,  0.5 <= m < 1 */
    /* normalised: val = (1 + mant/8) * 2^(exp-7), exp in [1,14] */
    int exp_biased = e - 1 + 7; /* because frexp gives m in [0.5,1) */
    if (exp_biased <= 0) {
        /* subnormal */
        int mant3 = (int)roundf(val * 64.0f); /* val * 2^6 */
        mant3 = mant3 < 0 ? 0 : (mant3 > 7 ? 7 : mant3);
        return sign | (uint8_t)mant3;
    }
    if (exp_biased > 14) exp_biased = 14; /* clamp to max normal */
    float base = ldexpf(1.0f, exp_biased - 7);
    int mant3 = (int)roundf((val / base - 1.0f) * 8.0f);
    mant3 = mant3 < 0 ? 0 : (mant3 > 7 ? 7 : mant3);
    return sign | ((uint8_t)exp_biased << 3) | (uint8_t)mant3;
}

/* ── bf16 helpers ────────────────────────────────────────────────────────── */
static float bf16_to_float(uint16_t v) {
    uint32_t bits = (uint32_t)v << 16;
    float f;
    memcpy(&f, &bits, 4);
    return f;
}

/* ── B preshuffle ────────────────────────────────────────────────────────── */
/*
 * Maps B_kn[K, N] → B_shuf[N/16, K/16, 2, 16, 8]
 *   B_shuf[n0, k0, klane, lane16, kpack] = B_kn[k0*16 + klane*8 + kpack, n0*16 + lane16]
 * Mirrors fly.rdna_fp8_preshuffle_gemm.preshuffle_b_fp8.
 */
static void preshuffle_b(const uint8_t *B_kn, uint8_t *B_shuf) {
    const int K0 = FP8_GEMM_K / 16;
    const int N0 = FP8_GEMM_N / 16;
    for (int n0 = 0; n0 < N0; n0++)
    for (int k0 = 0; k0 < K0; k0++)
    for (int klane = 0; klane < 2; klane++)
    for (int lane16 = 0; lane16 < 16; lane16++)
    for (int kpack = 0; kpack < 8; kpack++) {
        int src_k = k0 * 16 + klane * 8 + kpack;
        int src_n = n0 * 16 + lane16;
        int dst = (((n0 * K0 + k0) * 2 + klane) * 16 + lane16) * 8 + kpack;
        B_shuf[dst] = B_kn[src_k * FP8_GEMM_N + src_n];
    }
}

int main(int argc, char *argv[]) {
    int M = (argc > 1) ? atoi(argv[1]) : 256;
    if (M <= 0 || M % FP8_GEMM_TILE_M != 0) {
        fprintf(stderr, "M must be a positive multiple of %d (got %d)\n",
                FP8_GEMM_TILE_M, M);
        return 1;
    }
    const int N = FP8_GEMM_N;
    const int K = FP8_GEMM_K;
    printf("M=%d  N=%d  K=%d\n", M, N, K);

    /* ── Allocate host buffers ─────────────────────────────────────────────── */
    const size_t sz_A     = (size_t)M * K;            /* fp8, 1 byte each */
    const size_t sz_B_kn  = (size_t)K * N;            /* fp8 original     */
    const size_t sz_B_sh  = (size_t)K * N;            /* fp8 preshuffled  */
    const size_t sz_C     = (size_t)M * N * 2;        /* bf16, 2 bytes    */
    const size_t sz_sa    = (size_t)M * sizeof(float);
    const size_t sz_sb    = (size_t)N * sizeof(float);

    uint8_t  *h_A    = (uint8_t  *)malloc(sz_A);
    uint8_t  *h_B_kn = (uint8_t  *)malloc(sz_B_kn);
    uint8_t  *h_B_sh = (uint8_t  *)malloc(sz_B_sh);
    uint16_t *h_C    = (uint16_t *)malloc(sz_C);
    float    *h_sa   = (float    *)malloc(sz_sa);
    float    *h_sb   = (float    *)malloc(sz_sb);

    /* Fill A and B with fp8(1.0) = 0x38.
     * With scale_a = scale_b = 1.0 the expected output is
     * C[m,n] = sum_{k=0}^{K-1} 1.0 = K  (exact in bf16). */
    const uint8_t FP8_ONE = encode_fp8(1.0f);
    printf("fp8(1.0) = 0x%02x  (expected 0x38)\n", FP8_ONE);
    memset(h_A,    FP8_ONE, sz_A);
    memset(h_B_kn, FP8_ONE, sz_B_kn);
    for (int i = 0; i < M; i++) h_sa[i] = 1.0f;
    for (int i = 0; i < N; i++) h_sb[i] = 1.0f;

    /* Preshuffle B on host */
    printf("Preshuffling B (%zu MB)...\n", sz_B_sh >> 20);
    preshuffle_b(h_B_kn, h_B_sh);

    /* ── Allocate and upload device buffers ───────────────────────────────── */
    uint8_t  *d_A, *d_B_sh;
    uint16_t *d_C;
    float    *d_sa, *d_sb;

    CHECK_HIP(hipMalloc(&d_A,   sz_A));
    CHECK_HIP(hipMalloc(&d_B_sh, sz_B_sh));
    CHECK_HIP(hipMalloc(&d_C,   sz_C));
    CHECK_HIP(hipMalloc(&d_sa,  sz_sa));
    CHECK_HIP(hipMalloc(&d_sb,  sz_sb));

    CHECK_HIP(hipMemcpy(d_A,    h_A,    sz_A,   hipMemcpyHostToDevice));
    CHECK_HIP(hipMemcpy(d_B_sh, h_B_sh, sz_B_sh, hipMemcpyHostToDevice));
    CHECK_HIP(hipMemcpy(d_sa,   h_sa,   sz_sa,  hipMemcpyHostToDevice));
    CHECK_HIP(hipMemcpy(d_sb,   h_sb,   sz_sb,  hipMemcpyHostToDevice));

    /* ── Load module ──────────────────────────────────────────────────────── */
    fp8_gemm_Module_t mod = {};
    if (fp8_gemm_Module_Load(&mod, KERNEL_HSACO) != 0) return 1;

    /* ── Launch ───────────────────────────────────────────────────────────── */
    hipStream_t stream;
    CHECK_HIP(hipStreamCreate(&stream));

    if (fp8_gemm_wrapper(&mod,
                         (hipDeviceptr_t)d_C,
                         (hipDeviceptr_t)d_A,
                         (hipDeviceptr_t)d_B_sh,
                         (hipDeviceptr_t)d_sa,
                         (hipDeviceptr_t)d_sb,
                         (int32_t)M,
                         stream) != 0)
        return 1;

    CHECK_HIP(hipStreamSynchronize(stream));

    /* ── Copy result back ─────────────────────────────────────────────────── */
    CHECK_HIP(hipMemcpy(h_C, d_C, sz_C, hipMemcpyDeviceToHost));

    /* ── Verify: every element should be 6144.0 ──────────────────────────── */
    const float expected = (float)K;   /* 6144.0 */
    bool correct = true;
    int  mismatches = 0;
    for (int m = 0; m < M && mismatches < 5; m++) {
        for (int n = 0; n < N; n++) {
            float got = bf16_to_float(h_C[m * N + n]);
            if (fabsf(got - expected) > 0.5f) {
                fprintf(stderr, "Mismatch C[%d,%d]: got %.1f  expected %.1f\n",
                        m, n, (double)got, (double)expected);
                correct = false;
                if (++mismatches >= 5) break;
            }
        }
    }
    printf("Result correct (all C[m,n] == %.0f): %s\n",
           (double)expected, correct ? "true" : "false");

    /* ── Cleanup ──────────────────────────────────────────────────────────── */
    CHECK_HIP(hipStreamDestroy(stream));
    (void)hipFree(d_A);
    (void)hipFree(d_B_sh);
    (void)hipFree(d_C);
    (void)hipFree(d_sa);
    (void)hipFree(d_sb);
    fp8_gemm_Module_Unload(&mod);
    free(h_A); free(h_B_kn); free(h_B_sh);
    free(h_C); free(h_sa); free(h_sb);

    return correct ? 0 : 1;
}
